import { Category, Habit, Task } from '../types/todo';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'all', name: 'All Tasks', emoji: '🎀', color: 'pink' },
  { id: 'daily', name: 'Daily Routine', emoji: '🌸', color: 'rose' },
  { id: 'glam', name: 'Self-Care & Glam', emoji: '💄', color: 'fuchsia' },
  { id: 'study', name: 'Study & Learning', emoji: '📚', color: 'purple' },
  { id: 'career', name: 'Career & Work', emoji: '💼', color: 'emerald' },
  { id: 'shopping', name: 'Shopping', emoji: '🛍️', color: 'amber' },
  { id: 'travel', name: 'Travel', emoji: '✈️', color: 'sky' },
  { id: 'fitness', name: 'Fitness & Exercise', emoji: '💪', color: 'orange' },
  { id: 'food', name: 'Food & Cooking', emoji: '🍰', color: 'yellow' },
  { id: 'social', name: 'Social & Friends', emoji: '👯‍♀️', color: 'pink' },
  { id: 'home', name: 'Home & Chores', emoji: '🏡', color: 'teal' },
  { id: 'finance', name: 'Finance & Budget', emoji: '💰', color: 'green' },
  { id: 'creative', name: 'Creative & Art', emoji: '🎨', color: 'violet' },
  { id: 'health', name: 'Health & Wellness', emoji: '🌿', color: 'lime' },
  { id: 'beauty', name: 'Beauty & Skincare', emoji: '✨', color: 'rose' },
  { id: 'fashion', name: 'Fashion & Style', emoji: '👗', color: 'fuchsia' },
  { id: 'music', name: 'Music', emoji: '🎵', color: 'indigo' },
  { id: 'reading', name: 'Reading', emoji: '📖', color: 'amber' },
  { id: 'writing', name: 'Writing & Journaling', emoji: '✍️', color: 'stone' },
  { id: 'photography', name: 'Photography', emoji: '📸', color: 'cyan' },
  { id: 'gardening', name: 'Gardening & Plants', emoji: '🌱', color: 'green' },
  { id: 'pets', name: 'Pets & Animals', emoji: '🐾', color: 'orange' },
  { id: 'volunteer', name: 'Volunteering', emoji: '💝', color: 'rose' },
  { id: 'spiritual', name: 'Spiritual & Mindfulness', emoji: '🔮', color: 'purple' },
  { id: 'tech', name: 'Tech & Gadgets', emoji: '💻', color: 'slate' },
  { id: 'cleaning', name: 'Cleaning & Organizing', emoji: '🧹', color: 'sky' },
  { id: 'gifts', name: 'Gifts & Celebrations', emoji: '🎁', color: 'pink' },
  { id: 'events', name: 'Events & Parties', emoji: '🎉', color: 'amber' },
  { id: 'dating', name: 'Dating & Romance', emoji: '💕', color: 'rose' },
  { id: 'morning', name: 'Morning Routine', emoji: '🌅', color: 'orange' },
  { id: 'evening', name: 'Evening Routine', emoji: '🌙', color: 'indigo' },
  { id: 'weekend', name: 'Weekend Plans', emoji: '🌈', color: 'teal' },
  { id: 'urgent', name: 'Urgent & ASAP', emoji: '🚨', color: 'red' },
  { id: 'goals', name: 'Goals & Dreams', emoji: '🌟', color: 'yellow' },
  { id: 'sidehustle', name: 'Side Hustle', emoji: '💎', color: 'emerald' },
  { id: 'selflove', name: 'Self Love', emoji: '🩷', color: 'pink' },
  { id: 'gratitude', name: 'Gratitude', emoji: '🙏', color: 'amber' },
  { id: 'bucketlist', name: 'Bucket List', emoji: '⭐', color: 'violet' },
  { id: 'holiday', name: 'Holidays & Seasons', emoji: '🎄', color: 'green' },
  { id: 'workout', name: 'Workout Plan', emoji: '🏋️‍♀️', color: 'orange' },
  { id: 'mealprep', name: 'Meal Prep', emoji: '🥗', color: 'lime' },
  { id: 'errands', name: 'Errands & Chores', emoji: '📋', color: 'stone' },
  { id: 'calls', name: 'Calls & Emails', emoji: '📞', color: 'blue' },
  { id: 'online', name: 'Social Media', emoji: '📱', color: 'cyan' },
  { id: 'inspiration', name: 'Inspiration & Ideas', emoji: '💡', color: 'yellow' },
  { id: 'wishlist', name: 'Wishlist', emoji: '🛒', color: 'amber' },
  { id: 'savings', name: 'Savings & Investing', emoji: '🏦', color: 'green' },
  { id: 'networking', name: 'Networking', emoji: '🤝', color: 'blue' },
  { id: 'interview', name: 'Interviews & Applications', emoji: '🎤', color: 'purple' },
  { id: 'portfolio', name: 'Projects & Portfolio', emoji: '💼', color: 'slate' },
  { id: 'content', name: 'Content Creation', emoji: '🎬', color: 'red' },
  { id: 'gaming', name: 'Gaming', emoji: '🎮', color: 'violet' },
  { id: 'anime', name: 'Anime & Manga', emoji: '🍥', color: 'pink' },
  { id: 'movies', name: 'Movies & TV Shows', emoji: '🍿', color: 'amber' },
  { id: 'podcasts', name: 'Podcasts', emoji: '🎧', color: 'indigo' },
  { id: 'crafts', name: 'Crafts & DIY', emoji: '🧶', color: 'rose' },
  { id: 'baking', name: 'Baking & Desserts', emoji: '🧁', color: 'yellow' },
  { id: 'coffee', name: 'Coffee & Cafés', emoji: '☕', color: 'amber' },
  { id: 'tea', name: 'Tea Time', emoji: '🍵', color: 'green' },
  { id: 'brunch', name: 'Brunch & Breakfast', emoji: '🥞', color: 'orange' },
  { id: 'dining', name: 'Dining Out', emoji: '🍽️', color: 'red' },
  { id: 'recipes', name: 'Recipes to Try', emoji: '👩‍🍳', color: 'lime' },
  { id: 'restaurants', name: 'Restaurant Bucket List', emoji: '🍜', color: 'orange' },
  { id: 'desserts', name: 'Desserts & Sweets', emoji: '🍩', color: 'fuchsia' },
  { id: 'wine', name: 'Wine & Cheese', emoji: '🍷', color: 'red' },
  { id: 'cocktails', name: 'Cocktails & Drinks', emoji: '🍸', color: 'amber' },
  { id: 'yoga', name: 'Yoga & Meditation', emoji: '🧘‍♀️', color: 'teal' },
  { id: 'spa', name: 'Spa & Relaxation', emoji: '💆‍♀️', color: 'sky' },
  { id: 'hair', name: 'Hair & Nails', emoji: '💇‍♀️', color: 'pink' },
  { id: 'makeup', name: 'Makeup', emoji: '💋', color: 'rose' },
  { id: 'skincare', name: 'Skincare', emoji: '🧴', color: 'cyan' },
  { id: 'outfits', name: 'Outfit Planning', emoji: '👠', color: 'fuchsia' },
  { id: 'accessories', name: 'Accessories & Jewelry', emoji: '💍', color: 'amber' },
  { id: 'shoes', name: 'Shoes', emoji: '👡', color: 'red' },
  { id: 'bags', name: 'Bags & Purses', emoji: '👜', color: 'purple' },
  { id: 'perfume', name: 'Perfume & Fragrance', emoji: '🌸', color: 'pink' },
  { id: 'candles', name: 'Candles & Home Scents', emoji: '🕯️', color: 'amber' },
  { id: 'flowers', name: 'Flowers & Bouquets', emoji: '💐', color: 'rose' },
  { id: 'decor', name: 'Home Decor', emoji: '🛋️', color: 'teal' },
  { id: 'organization', name: 'Organization', emoji: '🗂️', color: 'blue' },
  { id: 'minimalism', name: 'Decluttering', emoji: '🧘', color: 'stone' },
  { id: 'sustainability', name: 'Sustainability', emoji: '🌍', color: 'green' },
  { id: 'budgeting', name: 'Budgeting', emoji: '💸', color: 'emerald' },
  { id: 'freelance', name: 'Freelance Work', emoji: '💻', color: 'slate' },
  { id: 'mindfulness', name: 'Mindfulness', emoji: '🧠', color: 'purple' },
  { id: 'therapy', name: 'Therapy & Healing', emoji: '💚', color: 'green' },
  { id: 'journaling', name: 'Journaling', emoji: '📓', color: 'stone' },
  { id: 'affirmations', name: 'Affirmations', emoji: '🗣️', color: 'pink' },
  { id: 'vision', name: 'Vision Board', emoji: '🖼️', color: 'violet' },
  { id: 'productivity', name: 'Productivity', emoji: '⚡', color: 'yellow' },
  { id: 'time-management', name: 'Time Management', emoji: '⏰', color: 'orange' },
  { id: 'focus', name: 'Deep Focus', emoji: '🎯', color: 'blue' },
  { id: 'discipline', name: 'Discipline', emoji: '💪', color: 'emerald' },
  { id: 'confidence', name: 'Confidence', emoji: '👑', color: 'amber' },
  { id: 'public-speaking', name: 'Public Speaking', emoji: '🎙️', color: 'purple' },
  { id: 'leadership', name: 'Leadership', emoji: '👸', color: 'rose' },
  { id: 'mentorship', name: 'Mentorship', emoji: '🌟', color: 'yellow' },
  { id: 'family', name: 'Family', emoji: '👨‍👩‍👧', color: 'orange' },
  { id: 'parenting', name: 'Parenting & Kids', emoji: '👶', color: 'yellow' },
  { id: 'friendship', name: 'Friendship', emoji: '👭', color: 'fuchsia' },
  { id: 'relationships', name: 'Relationships', emoji: '💑', color: 'rose' },
  { id: 'wedding', name: 'Wedding Planning', emoji: '👰', color: 'white' },
  { id: 'pet-care', name: 'Pet Care', emoji: '🐶', color: 'orange' },
  { id: 'nature', name: 'Nature & Outdoors', emoji: '🌲', color: 'green' },
  { id: 'hiking', name: 'Hiking & Trekking', emoji: '🥾', color: 'emerald' },
  { id: 'camping', name: 'Camping', emoji: '🏕️', color: 'green' },
  { id: 'beach', name: 'Beach & Ocean', emoji: '🏖️', color: 'sky' },
  { id: 'roadtrip', name: 'Road Trips', emoji: '🚗', color: 'blue' },
  { id: 'adventure', name: 'Adventure & Thrills', emoji: '🪂', color: 'orange' },
  { id: 'museums', name: 'Museums & Culture', emoji: '🏛️', color: 'purple' },
  { id: 'theater', name: 'Theater & Shows', emoji: '🎭', color: 'red' },
  { id: 'dance', name: 'Dance', emoji: '💃', color: 'pink' },
  { id: 'running', name: 'Running', emoji: '🏃‍♀️', color: 'red' },
  { id: 'swimming', name: 'Swimming', emoji: '🏊‍♀️', color: 'sky' },
  { id: 'cycling', name: 'Cycling', emoji: '🚴‍♀️', color: 'green' },
  { id: 'pilates', name: 'Pilates & Barre', emoji: '🤸', color: 'pink' },
  { id: 'hiit', name: 'HIIT & Cardio', emoji: '🔥', color: 'red' },
  { id: 'strength', name: 'Strength Training', emoji: '🏋️', color: 'slate' },
  { id: 'nutrition', name: 'Nutrition & Diet', emoji: '🥑', color: 'green' },
  { id: 'mental-health', name: 'Mental Health', emoji: '🧘', color: 'purple' },
  { id: 'sleep', name: 'Sleep & Rest', emoji: '😴', color: 'indigo' },
  { id: 'stress-relief', name: 'Stress Relief', emoji: '🌿', color: 'lime' },
  { id: 'self-care', name: 'Self-Care Day', emoji: '🛁', color: 'pink' },
  { id: 'digital-detox', name: 'Digital Detox', emoji: '📵', color: 'stone' },
  { id: 'stargazing', name: 'Stargazing', emoji: '🌌', color: 'indigo' },
  { id: 'new-year', name: 'New Year Goals', emoji: '🎆', color: 'purple' },
  { id: 'monthly', name: 'Monthly Goals', emoji: '📅', color: 'blue' },
  { id: 'weekly', name: 'Weekly Plans', emoji: '📋', color: 'teal' },
  { id: 'reflections', name: 'Reflections', emoji: '🪞', color: 'purple' },
  { id: 'growth', name: 'Personal Growth', emoji: '🌱', color: 'green' },
  { id: 'boundaries', name: 'Boundaries', emoji: '🚧', color: 'red' },
  { id: 'healing', name: 'Healing Journey', emoji: '💚', color: 'emerald' },
  { id: 'glow-up', name: 'Glow Up', emoji: '✨', color: 'fuchsia' },
  { id: 'milestones', name: 'Milestones', emoji: '🏅', color: 'amber' },
  { id: 'achievements', name: 'Achievements', emoji: '🏆', color: 'yellow' },
  { id: 'celebrations', name: 'Celebrations', emoji: '🎉', color: 'pink' },
  { id: 'pampering', name: 'Pampering', emoji: '💅', color: 'fuchsia' },
  { id: 'luxury', name: 'Luxury & Treats', emoji: '💎', color: 'purple' },
  { id: 'thrifting', name: 'Thrifting & Vintage', emoji: '👗', color: 'teal' },
  { id: 'capsule-wardrobe', name: 'Capsule Wardrobe', emoji: '👚', color: 'stone' },
  { id: 'athleisure', name: 'Athleisure', emoji: '🏃‍♀️', color: 'orange' },
  { id: 'formal', name: 'Formal & Business', emoji: '👔', color: 'slate' },
  { id: 'casual', name: 'Casual & Comfy', emoji: '👕', color: 'blue' },
  { id: 'loungewear', name: 'Loungewear', emoji: '🛋️', color: 'pink' },
  { id: 'activewear', name: 'Activewear', emoji: '🎽', color: 'green' },
  { id: 'swimwear', name: 'Swimwear', emoji: '👙', color: 'sky' },
  { id: 'nail-art', name: 'Nail Art', emoji: '💅', color: 'pink' },
  { id: 'hair-care', name: 'Hair Care', emoji: '💇‍♀️', color: 'purple' },
  { id: 'body-care', name: 'Body Care', emoji: '🧖‍♀️', color: 'sky' },
  { id: 'supplements', name: 'Supplements & Vitamins', emoji: '💊', color: 'green' },
  { id: 'meal-planning', name: 'Meal Planning', emoji: '📋', color: 'teal' },
  { id: 'grocery', name: 'Grocery Shopping', emoji: '🛒', color: 'green' },
  { id: 'cooking', name: 'Cooking', emoji: '👩‍🍳', color: 'orange' },
  { id: 'healthy-eating', name: 'Healthy Eating', emoji: '🥗', color: 'lime' },
  { id: 'vegan', name: 'Vegan & Plant-Based', emoji: '🌱', color: 'green' },
  { id: 'hydration', name: 'Hydration', emoji: '💧', color: 'sky' },
  { id: 'bedtime-routine', name: 'Bedtime Routine', emoji: '🌙', color: 'purple' },
  { id: 'morning-routine', name: 'Morning Routine', emoji: '🌅', color: 'orange' },
  { id: 'breathing', name: 'Breathing Exercises', emoji: '🌬️', color: 'sky' },
  { id: 'volunteering', name: 'Community Service', emoji: '🤲', color: 'rose' },
  { id: 'library', name: 'Library & Bookstores', emoji: '📚', color: 'blue' },
  { id: 'movies-night', name: 'Movie Nights', emoji: '🍿', color: 'indigo' },
  { id: 'boardgames', name: 'Board Games', emoji: '🎲', color: 'amber' },
  { id: 'karaoke', name: 'Karaoke', emoji: '🎙️', color: 'purple' },
  { id: 'bowling-night', name: 'Bowling', emoji: '🎳', color: 'violet' },
  { id: 'arcade', name: 'Arcade', emoji: '🕹️', color: 'fuchsia' },
  { id: 'mini-golf', name: 'Mini Golf', emoji: '⛳', color: 'lime' },
  { id: 'escape-room', name: 'Escape Room', emoji: '🗝️', color: 'stone' },
  { id: 'bowling-club', name: 'Clubs & Groups', emoji: '👥', color: 'teal' },
  { id: 'volunteer-work', name: 'Charity Work', emoji: '💝', color: 'rose' },
  { id: 'mentoring', name: 'Mentoring', emoji: '🧑‍🏫', color: 'emerald' },
  { id: 'public-speaking-event', name: 'Speaking Events', emoji: '🎤', color: 'red' },
  { id: 'sports', name: 'Sports', emoji: '⚽', color: 'green' },
  { id: 'basketball', name: 'Basketball', emoji: '🏀', color: 'orange' },
  { id: 'soccer', name: 'Soccer', emoji: '⚽', color: 'lime' },
  { id: 'tennis', name: 'Tennis', emoji: '🎾', color: 'yellow' },
  { id: 'golf', name: 'Golf', emoji: '⛳', color: 'emerald' },
  { id: 'skateboarding', name: 'Skateboarding', emoji: '🛹', color: 'stone' },
];

export const INITIAL_HABITS: Habit[] = [
  { id: 'h1', title: 'Morning Glass of Water & Lemon', emoji: '🍋', completedToday: true, streak: 4 },
  { id: 'h2', title: 'Gua Sha & Skincare Ritual', emoji: '🧖‍♀️', completedToday: true, streak: 7 },
  { id: 'h3', title: 'Pilates or 20-min Hot Girl Walk', emoji: '🎧', completedToday: false, streak: 3 },
  { id: 'h4', title: 'Read 15 pages of inspiring book', emoji: '📖', completedToday: false, streak: 5 },
  { id: 'h5', title: 'Write 3 things I am grateful for', emoji: '✨', completedToday: false, streak: 12 },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 't-1',
    title: 'Morning Matcha Latte & Romanticize Breakfast 🍵✨',
    notes: 'Whisk ceremonial grade matcha, toast sourdough with avocado, light a rose candle.',
    completed: true,
    completedAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    createdAt: new Date().toISOString(),
    dueDate: new Date().toISOString().split('T')[0],
    dueTime: '09:00',
    priority: 'important',
    energy: 'cozy',
    category: 'daily',
    isPinned: true,
    subtasks: [
      { id: 'st-1', text: 'Whisk ceremonial grade matcha', completed: true },
      { id: 'st-2', text: 'Toast sourdough bread with avocado', completed: true },
      { id: 'st-3', text: 'Light rose candle', completed: true },
    ],
    recurring: 'daily',
    tags: ['morning routine', 'matcha', 'cozy'],
  },
  {
    id: 't-2',
    title: 'Submit Project Presentation Deck 🎀💻',
    notes: 'Double check charts, pastel color schemes, and export PDF deck for the team.',
    completed: false,
    createdAt: new Date().toISOString(),
    dueDate: new Date().toISOString().split('T')[0],
    dueTime: '15:30',
    priority: 'urgent',
    energy: 'boss',
    category: 'career',
    isPinned: true,
    subtasks: [
      { id: 'st-4', text: 'Review slide typography & spacing', completed: true },
      { id: 'st-5', text: 'Write executive summary bullet points', completed: false },
      { id: 'st-6', text: 'Send email to team with link', completed: false },
    ],
    recurring: 'none',
    tags: ['deadline', 'work', 'girlboss'],
  },
  {
    id: 't-3',
    title: 'Evening Self-Care & Korean Face Mask 🧖‍♀️✨',
    notes: 'Hyaluronic acid serum, deep repair hair mask, and lavender pillow mist.',
    completed: false,
    createdAt: new Date().toISOString(),
    dueDate: new Date().toISOString().split('T')[0],
    dueTime: '21:00',
    priority: 'important',
    energy: 'cozy',
    category: 'glam',
    isPinned: false,
    subtasks: [
      { id: 'st-7', text: 'Double cleanse with cleansing balm', completed: false },
      { id: 'st-8', text: 'Put on sheet mask for 20 mins', completed: false },
      { id: 'st-9', text: 'Sip chamomile tea with honey', completed: false },
    ],
    recurring: 'none',
    tags: ['skincare', 'glow-up', 'relax'],
  },
  {
    id: 't-4',
    title: 'Order Fresh Pink Peonies & Strawberries 💐🍓',
    notes: 'Local farmers market or florist shop on 5th avenue.',
    completed: false,
    createdAt: new Date().toISOString(),
    dueDate: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    priority: 'soft',
    energy: 'flow',
    category: 'shopping',
    isPinned: false,
    subtasks: [],
    recurring: 'weekly',
    tags: ['aesthetic', 'home', 'flowers'],
  },
  {
    id: 't-5',
    title: 'Finish 2 chapters of French History & Vocabulary 🇫🇷📚',
    notes: 'Practice Duolingo streak and write down 10 new chic adjectives.',
    completed: false,
    createdAt: new Date().toISOString(),
    dueDate: new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0],
    priority: 'soft',
    energy: 'flow',
    category: 'study',
    isPinned: false,
    subtasks: [
      { id: 'st-10', text: '25 min focus timer', completed: false },
      { id: 'st-11', text: 'Review flashcards on phone', completed: false },
    ],
    recurring: 'none',
    tags: ['languages', 'smart girl', 'paris'],
  },
];
