import { Category, Habit, Task } from '../types/todo';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'all', name: 'All Cute Tasks', emoji: '🎀', color: 'pink' },
  { id: 'daily', name: 'Daily Routine', emoji: '🌸', color: 'rose' },
  { id: 'glam', name: 'Self-Care & Glam', emoji: '💄', color: 'fuchsia' },
  { id: 'study', name: 'Smart Girl Era', emoji: '📚', color: 'purple' },
  { id: 'career', name: 'Girl Boss Moves', emoji: '💼', color: 'emerald' },
  { id: 'shopping', name: 'Pink Wishlist', emoji: '🛍️', color: 'amber' },
  { id: 'travel', name: 'Dream Destinations', emoji: '✈️', color: 'sky' },
  { id: 'fitness', name: 'Hot Girl Energy', emoji: '💪', color: 'orange' },
  { id: 'food', name: 'Foodie Adventures', emoji: '🍰', color: 'yellow' },
  { id: 'social', name: 'Bestie Time', emoji: '👯‍♀️', color: 'pink' },
  { id: 'home', name: 'Cozy Home', emoji: '🏡', color: 'teal' },
  { id: 'finance', name: 'Money Moves', emoji: '💰', color: 'green' },
  { id: 'creative', name: 'Creative Spark', emoji: '🎨', color: 'violet' },
  { id: 'health', name: 'Health & Wellness', emoji: '🌿', color: 'lime' },
  { id: 'beauty', name: 'Beauty & Skincare', emoji: '✨', color: 'rose' },
  { id: 'fashion', name: 'Fashion & Style', emoji: '👗', color: 'fuchsia' },
  { id: 'music', name: 'Music & Vibes', emoji: '🎵', color: 'indigo' },
  { id: 'reading', name: 'Book Club', emoji: '📖', color: 'amber' },
  { id: 'writing', name: 'Writing & Journaling', emoji: '✍️', color: 'stone' },
  { id: 'photography', name: 'Photo Moments', emoji: '📸', color: 'cyan' },
  { id: 'gardening', name: 'Garden & Plants', emoji: '🌱', color: 'green' },
  { id: 'pets', name: 'Pet Love', emoji: '🐾', color: 'orange' },
  { id: 'volunteer', name: 'Kindness & Giving', emoji: '💝', color: 'rose' },
  { id: 'spiritual', name: 'Soul & Spirit', emoji: '🔮', color: 'purple' },
  { id: 'tech', name: 'Tech & Gadgets', emoji: '💻', color: 'slate' },
  { id: 'cleaning', name: 'Clean & Organize', emoji: '🧹', color: 'sky' },
  { id: 'gift', name: 'Gifts & Surprises', emoji: '🎁', color: 'pink' },
  { id: 'party', name: 'Party & Events', emoji: '🎉', color: 'amber' },
  { id: 'date', name: 'Date Night', emoji: '💕', color: 'rose' },
  { id: 'morning', name: 'Morning Rituals', emoji: '🌅', color: 'orange' },
  { id: 'evening', name: 'Evening Wind-Down', emoji: '🌙', color: 'indigo' },
  { id: 'weekend', name: 'Weekend Plans', emoji: '🌈', color: 'teal' },
  { id: 'urgent', name: 'Urgent & ASAP', emoji: '🚨', color: 'red' },
  { id: 'longterm', name: 'Big Dreams', emoji: '🌟', color: 'yellow' },
  { id: 'learning', name: 'Learn & Grow', emoji: '🎓', color: 'blue' },
  { id: 'sidehustle', name: 'Side Hustle', emoji: '💎', color: 'emerald' },
  { id: 'selflove', name: 'Self Love', emoji: '🩷', color: 'pink' },
  { id: 'gratitude', name: 'Gratitude List', emoji: '🙏', color: 'amber' },
  { id: 'bucketlist', name: 'Bucket List', emoji: '⭐', color: 'violet' },
  { id: 'seasonal', name: 'Seasonal Fun', emoji: '❄️', color: 'sky' },
  { id: 'holiday', name: 'Holiday Prep', emoji: '🎄', color: 'green' },
  { id: 'workout', name: 'Workout Plan', emoji: '🏋️‍♀️', color: 'orange' },
  { id: 'mealprep', name: 'Meal Prep', emoji: '🥗', color: 'lime' },
  { id: 'errands', name: 'Errands & Chores', emoji: '📋', color: 'stone' },
  { id: 'calls', name: 'Calls & Emails', emoji: '📞', color: 'blue' },
  { id: 'online', name: 'Online & Social', emoji: '📱', color: 'cyan' },
  { id: 'inspiration', name: 'Inspiration Board', emoji: '💡', color: 'yellow' },
  { id: 'wishlist', name: 'Wishlist', emoji: '🛒', color: 'amber' },
  { id: 'savings', name: 'Savings Goals', emoji: '🏦', color: 'green' },
  { id: 'career-dev', name: 'Career Growth', emoji: '📈', color: 'emerald' },
  { id: 'networking', name: 'Networking', emoji: '🤝', color: 'blue' },
  { id: 'interview', name: 'Interviews', emoji: '🎤', color: 'purple' },
  { id: 'portfolio', name: 'Portfolio & Work', emoji: '💼', color: 'slate' },
  { id: 'blog', name: 'Blog & Content', emoji: '📝', color: 'pink' },
  { id: 'youtube', name: 'YouTube & Video', emoji: '🎬', color: 'red' },
  { id: 'instagram', name: 'Instagram & Reels', emoji: '📷', color: 'fuchsia' },
  { id: 'tiktok', name: 'TikTok & Trends', emoji: '🎭', color: 'slate' },
  { id: 'streaming', name: 'Streaming & Gaming', emoji: '🎮', color: 'violet' },
  { id: 'anime', name: 'Anime & Manga', emoji: '🍥', color: 'pink' },
  { id: 'kpop', name: 'K-Pop & Music', emoji: '🎤', color: 'purple' },
  { id: 'movies', name: 'Movies & Shows', emoji: '🍿', color: 'amber' },
  { id: 'podcasts', name: 'Podcasts & Audio', emoji: '🎧', color: 'indigo' },
  { id: 'crafts', name: 'Crafts & DIY', emoji: '🧶', color: 'rose' },
  { id: 'baking', name: 'Baking & Treats', emoji: '🧁', color: 'yellow' },
  { id: 'coffee', name: 'Coffee & Cafés', emoji: '☕', color: 'amber' },
  { id: 'tea', name: 'Tea Time', emoji: '🍵', color: 'green' },
  { id: 'brunch', name: 'Brunch & Breakfast', emoji: '🥞', color: 'orange' },
  { id: 'dinner', name: 'Dinner Plans', emoji: '🍽️', color: 'red' },
  { id: 'recipes', name: 'Recipes to Try', emoji: '👩‍🍳', color: 'lime' },
  { id: 'restaurants', name: 'Restaurant Bucket List', emoji: '🍜', color: 'orange' },
  { id: 'bubbletea', name: 'Bubble Tea Runs', emoji: '🧋', color: 'pink' },
  { id: 'dessert', name: 'Dessert & Sweets', emoji: '🍩', color: 'fuchsia' },
  { id: 'wine', name: 'Wine & Cheese', emoji: '🍷', color: 'red' },
  { id: 'cocktails', name: 'Cocktail Hour', emoji: '🍸', color: 'amber' },
  { id: 'yoga', name: 'Yoga & Meditation', emoji: '🧘‍♀️', color: 'teal' },
  { id: 'spa', name: 'Spa & Relaxation', emoji: '💆‍♀️', color: 'sky' },
  { id: 'hair', name: 'Hair & Nails', emoji: '💇‍♀️', color: 'pink' },
  { id: 'makeup', name: 'Makeup & Beauty', emoji: '💋', color: 'rose' },
  { id: 'skincare', name: 'Skincare Routine', emoji: '🧴', color: 'cyan' },
  { id: 'outfits', name: 'Outfit Planning', emoji: '👠', color: 'fuchsia' },
  { id: 'accessories', name: 'Accessories & Jewelry', emoji: '💍', color: 'amber' },
  { id: 'shoes', name: 'Shoe Collection', emoji: '👡', color: 'red' },
  { id: 'bags', name: 'Bags & Purses', emoji: '👜', color: 'purple' },
  { id: 'perfume', name: 'Perfume & Scents', emoji: '🌸', color: 'pink' },
  { id: 'candles', name: 'Candles & Aromas', emoji: '🕯️', color: 'amber' },
  { id: 'flowers', name: 'Flowers & Bouquets', emoji: '💐', color: 'rose' },
  { id: 'decor', name: 'Home Decor', emoji: '🛋️', color: 'teal' },
  { id: 'organization', name: 'Organization', emoji: '🗂️', color: 'blue' },
  { id: 'minimalism', name: 'Declutter & Minimal', emoji: '🧘', color: 'stone' },
  { id: 'sustainability', name: 'Eco & Green Living', emoji: '🌍', color: 'green' },
  { id: 'budget', name: 'Budget & Savings', emoji: '💸', color: 'emerald' },
  { id: 'investing', name: 'Investing & Stocks', emoji: '📊', color: 'blue' },
  { id: 'crypto', name: 'Crypto & Web3', emoji: '🪙', color: 'amber' },
  { id: 'freelance', name: 'Freelance Gigs', emoji: '💻', color: 'slate' },
  { id: 'mindfulness', name: 'Mindfulness', emoji: '🧠', color: 'purple' },
  { id: 'therapy', name: 'Therapy & Healing', emoji: '💚', color: 'green' },
  { id: 'journaling', name: 'Journaling', emoji: '📓', color: 'stone' },
  { id: 'affirmations', name: 'Affirmations', emoji: '🗣️', color: 'pink' },
  { id: 'goals', name: 'Goal Setting', emoji: '🎯', color: 'red' },
  { id: 'vision', name: 'Vision Board', emoji: '🖼️', color: 'violet' },
  { id: 'productivity', name: 'Productivity', emoji: '⚡', color: 'yellow' },
  { id: 'time-management', name: 'Time Management', emoji: '⏰', color: 'orange' },
  { id: 'focus', name: 'Deep Focus', emoji: '🎯', color: 'blue' },
  { id: 'discipline', name: 'Discipline & Willpower', emoji: '💪', color: 'emerald' },
  { id: 'confidence', name: 'Confidence Boost', emoji: '👑', color: 'amber' },
  { id: 'public-speaking', name: 'Public Speaking', emoji: '🎙️', color: 'purple' },
  { id: 'leadership', name: 'Leadership', emoji: '👸', color: 'rose' },
  { id: 'mentorship', name: 'Mentorship', emoji: '🌟', color: 'yellow' },
  { id: 'collaboration', name: 'Collaboration', emoji: '🤝', color: 'blue' },
  { id: 'community', name: 'Community & Friends', emoji: '🏘️', color: 'teal' },
  { id: 'family', name: 'Family Time', emoji: '👨‍👩‍👧', color: 'orange' },
  { id: 'parents', name: 'Parents & Elders', emoji: '👵', color: 'amber' },
  { id: 'siblings', name: 'Siblings', emoji: '👫', color: 'pink' },
  { id: 'partner', name: 'Partner & Love', emoji: '💑', color: 'rose' },
  { id: 'friendship', name: 'Friendship Goals', emoji: '👭', color: 'fuchsia' },
  { id: 'reunion', name: 'Reunions & Meetups', emoji: '🎊', color: 'amber' },
  { id: 'birthday', name: 'Birthdays', emoji: '🎂', color: 'pink' },
  { id: 'anniversary', name: 'Anniversaries', emoji: '💍', color: 'rose' },
  { id: 'wedding', name: 'Wedding Planning', emoji: '👰', color: 'white' },
  { id: 'baby', name: 'Baby & Kids', emoji: '👶', color: 'yellow' },
  { id: 'pets-care', name: 'Pet Care & Vet', emoji: '🐶', color: 'orange' },
  { id: 'adoption', name: 'Adoption & Rescue', emoji: '🐱', color: 'pink' },
  { id: 'wildlife', name: 'Wildlife & Nature', emoji: '🦋', color: 'green' },
  { id: 'ocean', name: 'Ocean & Beach', emoji: '🌊', color: 'sky' },
  { id: 'mountains', name: 'Mountains & Hiking', emoji: '⛰️', color: 'emerald' },
  { id: 'camping', name: 'Camping & Outdoors', emoji: '🏕️', color: 'green' },
  { id: 'roadtrip', name: 'Road Trips', emoji: '🚗', color: 'blue' },
  { id: 'adventure', name: 'Adventure & Thrills', emoji: '🪂', color: 'orange' },
  { id: 'culture', name: 'Culture & Arts', emoji: '🏛️', color: 'purple' },
  { id: 'museums', name: 'Museums & Galleries', emoji: '🖼️', color: 'stone' },
  { id: 'theater', name: 'Theater & Shows', emoji: '🎭', color: 'red' },
  { id: 'dance', name: 'Dance & Choreography', emoji: '💃', color: 'pink' },
  { id: 'running', name: 'Running & Marathons', emoji: '🏃‍♀️', color: 'red' },
  { id: 'swimming', name: 'Swimming & Pool', emoji: '🏊‍♀️', color: 'sky' },
  { id: 'cycling', name: 'Cycling & Biking', emoji: '🚴‍♀️', color: 'green' },
  { id: 'pilates', name: 'Pilates & Barre', emoji: '🤸', color: 'pink' },
  { id: 'hiit', name: 'HIIT & Cardio', emoji: '🔥', color: 'red' },
  { id: 'strength', name: 'Strength Training', emoji: '🏋️', color: 'slate' },
  { id: 'flexibility', name: 'Flexibility & Stretch', emoji: '🤸‍♀️', color: 'teal' },
  { id: 'nutrition', name: 'Nutrition & Diet', emoji: '🥑', color: 'green' },
  { id: 'mental-health', name: 'Mental Health', emoji: '🧠', color: 'purple' },
  { id: 'sleep', name: 'Sleep & Rest', emoji: '😴', color: 'indigo' },
  { id: 'stress-relief', name: 'Stress Relief', emoji: '🌿', color: 'lime' },
  { id: 'self-care-sunday', name: 'Self-Care Sunday', emoji: '🛁', color: 'pink' },
  { id: 'digital-detox', name: 'Digital Detox', emoji: '📵', color: 'stone' },
  { id: 'nature', name: 'Nature & Outdoors', emoji: '🌲', color: 'green' },
  { id: 'sunrise', name: 'Sunrise & Sunsets', emoji: '🌅', color: 'orange' },
  { id: 'stargazing', name: 'Stargazing', emoji: '🌌', color: 'indigo' },
  { id: 'rainy-day', name: 'Rainy Day Vibes', emoji: '🌧️', color: 'sky' },
  { id: 'snow-day', name: 'Snow Day Fun', emoji: '❄️', color: 'cyan' },
  { id: 'spring', name: 'Spring Cleaning', emoji: '🌷', color: 'green' },
  { id: 'summer', name: 'Summer Vibes', emoji: '☀️', color: 'yellow' },
  { id: 'autumn', name: 'Autumn Cozy', emoji: '🍂', color: 'orange' },
  { id: 'winter', name: 'Winter Wonderland', emoji: '⛄', color: 'sky' },
  { id: 'new-year', name: 'New Year Goals', emoji: '🎆', color: 'purple' },
  { id: 'resolution', name: 'Resolutions', emoji: '✨', color: 'amber' },
  { id: 'monthly', name: 'Monthly Goals', emoji: '📅', color: 'blue' },
  { id: 'weekly', name: 'Weekly Plans', emoji: '📋', color: 'teal' },
  { id: 'daily-affirmation', name: 'Daily Affirmations', emoji: '🌞', color: 'yellow' },
  { id: 'gratitude-daily', name: 'Daily Gratitude', emoji: '🙏', color: 'rose' },
  { id: 'wins', name: 'Daily Wins', emoji: '🏆', color: 'amber' },
  { id: 'reflections', name: 'Reflections', emoji: '🪞', color: 'purple' },
  { id: 'growth', name: 'Personal Growth', emoji: '🌱', color: 'green' },
  { id: 'boundaries', name: 'Boundaries & No', emoji: '🚧', color: 'red' },
  { id: 'healing', name: 'Healing Journey', emoji: '💚', color: 'emerald' },
  { id: 'forgiveness', name: 'Forgiveness', emoji: '🕊️', color: 'sky' },
  { id: 'letting-go', name: 'Letting Go', emoji: '🎈', color: 'pink' },
  { id: 'new-beginnings', name: 'New Beginnings', emoji: '🌅', color: 'orange' },
  { id: 'fresh-start', name: 'Fresh Start', emoji: '🆕', color: 'blue' },
  { id: 'transformation', name: 'Transformation', emoji: '🦋', color: 'violet' },
  { id: 'glow-up', name: 'Glow Up Journey', emoji: '✨', color: 'fuchsia' },
  { id: 'level-up', name: 'Level Up', emoji: '⬆️', color: 'emerald' },
  { id: 'milestones', name: 'Milestones', emoji: '🏅', color: 'amber' },
  { id: 'achievements', name: 'Achievements', emoji: '🏆', color: 'yellow' },
  { id: 'celebrations', name: 'Celebrations', emoji: '🎉', color: 'pink' },
  { id: 'rewards', name: 'Rewards & Treats', emoji: '🎁', color: 'rose' },
  { id: 'pampering', name: 'Pampering Time', emoji: '💅', color: 'fuchsia' },
  { id: 'indulgence', name: 'Indulgence', emoji: '🍫', color: 'amber' },
  { id: 'luxury', name: 'Luxury & Treats', emoji: '💎', color: 'purple' },
  { id: 'shopping-spree', name: 'Shopping Spree', emoji: '🛍️', color: 'pink' },
  { id: 'online-shopping', name: 'Online Shopping', emoji: '📦', color: 'blue' },
  { id: 'thrifting', name: 'Thrifting & Vintage', emoji: '👗', color: 'teal' },
  { id: 'sustainable-fashion', name: 'Sustainable Fashion', emoji: '♻️', color: 'green' },
  { id: 'capsule-wardrobe', name: 'Capsule Wardrobe', emoji: '👚', color: 'stone' },
  { id: 'minimalist-fashion', name: 'Minimalist Fashion', emoji: '🖤', color: 'slate' },
  { id: 'streetwear', name: 'Streetwear', emoji: '🧢', color: 'black' },
  { id: 'athleisure', name: 'Athleisure', emoji: '🏃‍♀️', color: 'orange' },
  { id: 'formal', name: 'Formal & Business', emoji: '👔', color: 'slate' },
  { id: 'casual', name: 'Casual & Comfy', emoji: '👕', color: 'blue' },
  { id: 'loungewear', name: 'Loungewear', emoji: '🛋️', color: 'pink' },
  { id: 'activewear', name: 'Activewear', emoji: '🎽', color: 'green' },
  { id: 'swimwear', name: 'Swimwear', emoji: '👙', color: 'sky' },
  { id: 'lingerie', name: 'Lingerie', emoji: '🩱', color: 'rose' },
  { id: 'pajamas', name: 'Pajamas & Sleepwear', emoji: '😴', color: 'indigo' },
  { id: 'seasonal-wardrobe', name: 'Seasonal Wardrobe', emoji: '🍁', color: 'orange' },
  { id: 'accessories-collection', name: 'Accessories Collection', emoji: '💍', color: 'amber' },
  { id: 'shoe-collection', name: 'Shoe Collection', emoji: '👠', color: 'red' },
  { id: 'bag-collection', name: 'Bag Collection', emoji: '👜', color: 'purple' },
  { id: 'jewelry', name: 'Jewelry & Watches', emoji: '⌚', color: 'yellow' },
  { id: 'sunglasses', name: 'Sunglasses', emoji: '🕶️', color: 'slate' },
  { id: 'hats', name: 'Hats & Caps', emoji: '🧢', color: 'blue' },
  { id: 'scarves', name: 'Scarves & Wraps', emoji: '🧣', color: 'red' },
  { id: 'belts', name: 'Belts', emoji: '🔗', color: 'stone' },
  { id: 'hair-accessories', name: 'Hair Accessories', emoji: '🎀', color: 'pink' },
  { id: 'makeup-collection', name: 'Makeup Collection', emoji: '💄', color: 'fuchsia' },
  { id: 'skincare-collection', name: 'Skincare Collection', emoji: '🧴', color: 'cyan' },
  { id: 'perfume-collection', name: 'Perfume Collection', emoji: '🌸', color: 'rose' },
  { id: 'nail-art', name: 'Nail Art & Designs', emoji: '💅', color: 'pink' },
  { id: 'hair-care', name: 'Hair Care & Treatments', emoji: '💇‍♀️', color: 'purple' },
  { id: 'body-care', name: 'Body Care', emoji: '🧖‍♀️', color: 'sky' },
  { id: 'oral-care', name: 'Oral Care', emoji: '🦷', color: 'blue' },
  { id: 'supplements', name: 'Supplements & Vitamins', emoji: '💊', color: 'green' },
  { id: 'fitness-tracker', name: 'Fitness Tracker', emoji: '⌚', color: 'orange' },
  { id: 'meal-planning', name: 'Meal Planning', emoji: '📋', color: 'teal' },
  { id: 'grocery', name: 'Grocery Shopping', emoji: '🛒', color: 'green' },
  { id: 'cooking', name: 'Cooking & Recipes', emoji: '👩‍🍳', color: 'orange' },
  { id: 'baking-bread', name: 'Baking Bread', emoji: '🍞', color: 'amber' },
  { id: 'dessert-baking', name: 'Dessert Baking', emoji: '🧁', color: 'pink' },
  { id: 'cake-decorating', name: 'Cake Decorating', emoji: '🎂', color: 'rose' },
  { id: 'chocolate', name: 'Chocolate Making', emoji: '🍫', color: 'amber' },
  { id: 'coffee-brewing', name: 'Coffee Brewing', emoji: '☕', color: 'brown' },
  { id: 'tea-blending', name: 'Tea Blending', emoji: '🍵', color: 'green' },
  { id: 'wine-tasting', name: 'Wine Tasting', emoji: '🍷', color: 'red' },
  { id: 'cocktail-making', name: 'Cocktail Making', emoji: '🍸', color: 'amber' },
  { id: 'beer-craft', name: 'Craft Beer', emoji: '🍺', color: 'yellow' },
  { id: 'mocktails', name: 'Mocktails', emoji: '🥤', color: 'pink' },
  { id: 'smoothies', name: 'Smoothies & Juices', emoji: '🥤', color: 'green' },
  { id: 'healthy-eating', name: 'Healthy Eating', emoji: '🥗', color: 'lime' },
  { id: 'vegan', name: 'Vegan & Plant-Based', emoji: '🌱', color: 'green' },
  { id: 'vegetarian', name: 'Vegetarian', emoji: '🥬', color: 'green' },
  { id: 'gluten-free', name: 'Gluten-Free', emoji: '🌾', color: 'amber' },
  { id: 'dairy-free', name: 'Dairy-Free', emoji: '🥛', color: 'blue' },
  { id: 'keto', name: 'Keto & Low-Carb', emoji: '🥑', color: 'green' },
  { id: 'paleo', name: 'Paleo Diet', emoji: '🍖', color: 'red' },
  { id: 'intermittent-fasting', name: 'Intermittent Fasting', emoji: '⏰', color: 'purple' },
  { id: 'intuitive-eating', name: 'Intuitive Eating', emoji: '🧘‍♀️', color: 'teal' },
  { id: 'mindful-eating', name: 'Mindful Eating', emoji: '🍽️', color: 'blue' },
  { id: 'portion-control', name: 'Portion Control', emoji: '⚖️', color: 'slate' },
  { id: 'hydration', name: 'Hydration Goals', emoji: '💧', color: 'sky' },
  { id: 'water-tracking', name: 'Water Tracking', emoji: '🥤', color: 'cyan' },
  { id: 'sleep-hygiene', name: 'Sleep Hygiene', emoji: '🛏️', color: 'indigo' },
  { id: 'bedtime-routine', name: 'Bedtime Routine', emoji: '🌙', color: 'purple' },
  { id: 'morning-routine', name: 'Morning Routine', emoji: '🌅', color: 'orange' },
  { id: 'skincare-morning', name: 'Morning Skincare', emoji: '☀️', color: 'yellow' },
  { id: 'skincare-night', name: 'Night Skincare', emoji: '🌙', color: 'indigo' },
  { id: 'makeup-routine', name: 'Makeup Routine', emoji: '💄', color: 'pink' },
  { id: 'hair-routine', name: 'Hair Routine', emoji: '💇‍♀️', color: 'purple' },
  { id: 'body-routine', name: 'Body Care Routine', emoji: '🧖‍♀️', color: 'sky' },
  { id: 'oral-routine', name: 'Oral Care Routine', emoji: '🦷', color: 'blue' },
  { id: 'fitness-routine', name: 'Fitness Routine', emoji: '💪', color: 'orange' },
  { id: 'workout-routine', name: 'Workout Routine', emoji: '🏋️‍♀️', color: 'red' },
  { id: 'cardio-routine', name: 'Cardio Routine', emoji: '🏃‍♀️', color: 'red' },
  { id: 'strength-routine', name: 'Strength Routine', emoji: '🏋️', color: 'slate' },
  { id: 'flexibility-routine', name: 'Flexibility Routine', emoji: '🤸‍♀️', color: 'teal' },
  { id: 'yoga-routine', name: 'Yoga Routine', emoji: '🧘‍♀️', color: 'teal' },
  { id: 'meditation-routine', name: 'Meditation Routine', emoji: '🧘', color: 'purple' },
  { id: 'breathing', name: 'Breathing Exercises', emoji: '🌬️', color: 'sky' },
  { id: 'journaling-routine', name: 'Journaling Routine', emoji: '📓', color: 'stone' },
  { id: 'reading-routine', name: 'Reading Routine', emoji: '📚', color: 'amber' },
  { id: 'learning-routine', name: 'Learning Routine', emoji: '🎓', color: 'blue' },
  { id: 'creative-routine', name: 'Creative Routine', emoji: '🎨', color: 'violet' },
  { id: 'practice', name: 'Practice & Rehearsal', emoji: '🎵', color: 'indigo' },
  { id: 'rehearsal', name: 'Rehearsals', emoji: '🎭', color: 'red' },
  { id: 'performance', name: 'Performances', emoji: '🎤', color: 'purple' },
  { id: 'competition', name: 'Competitions', emoji: '🏆', color: 'amber' },
  { id: 'tournament', name: 'Tournaments', emoji: '⚔️', color: 'red' },
  { id: 'league', name: 'Leagues & Teams', emoji: '🏅', color: 'blue' },
  { id: 'club', name: 'Clubs & Groups', emoji: '👥', color: 'teal' },
  { id: 'team', name: 'Team Activities', emoji: '🤝', color: 'green' },
  { id: 'solo', name: 'Solo Activities', emoji: '🧍‍♀️', color: 'slate' },
  { id: 'partner-activities', name: 'Partner Activities', emoji: '👫', color: 'pink' },
  { id: 'group-activities', name: 'Group Activities', emoji: '👯‍♀️', color: 'fuchsia' },
  { id: 'family-activities', name: 'Family Activities', emoji: '👨‍👩‍👧', color: 'orange' },
  { id: 'kids-activities', name: 'Kids Activities', emoji: '🧒', color: 'yellow' },
  { id: 'teen-activities', name: 'Teen Activities', emoji: '🧑', color: 'blue' },
  { id: 'adult-activities', name: 'Adult Activities', emoji: '👩', color: 'purple' },
  { id: 'senior-activities', name: 'Senior Activities', emoji: '👵', color: 'amber' },
  { id: 'all-ages', name: 'All Ages Fun', emoji: '🎊', color: 'pink' },
  { id: 'indoor', name: 'Indoor Fun', emoji: '🏠', color: 'teal' },
  { id: 'outdoor', name: 'Outdoor Fun', emoji: '🌳', color: 'green' },
  { id: 'rainy-day-activities', name: 'Rainy Day Activities', emoji: '🌧️', color: 'sky' },
  { id: 'snow-day-activities', name: 'Snow Day Activities', emoji: '❄️', color: 'cyan' },
  { id: 'sunny-day', name: 'Sunny Day Fun', emoji: '☀️', color: 'yellow' },
  { id: 'windy-day', name: 'Windy Day Fun', emoji: '💨', color: 'slate' },
  { id: 'cloudy-day', name: 'Cloudy Day Fun', emoji: '☁️', color: 'gray' },
  { id: 'spring-activities', name: 'Spring Activities', emoji: '🌷', color: 'green' },
  { id: 'summer-activities', name: 'Summer Activities', emoji: '☀️', color: 'yellow' },
  { id: 'autumn-activities', name: 'Autumn Activities', emoji: '🍂', color: 'orange' },
  { id: 'winter-activities', name: 'Winter Activities', emoji: '⛄', color: 'sky' },
  { id: 'holiday-activities', name: 'Holiday Activities', emoji: '🎄', color: 'green' },
  { id: 'christmas', name: 'Christmas Fun', emoji: '🎅', color: 'red' },
  { id: 'halloween', name: 'Halloween Fun', emoji: '🎃', color: 'orange' },
  { id: 'thanksgiving', name: 'Thanksgiving', emoji: '🦃', color: 'amber' },
  { id: 'easter', name: 'Easter Fun', emoji: '🐰', color: 'pink' },
  { id: 'valentines', name: "Valentine's Day", emoji: '💕', color: 'rose' },
  { id: 'new-year-eve', name: "New Year's Eve", emoji: '🎆', color: 'purple' },
  { id: 'independence', name: 'Independence Day', emoji: '🎆', color: 'red' },
  { id: 'birthday-party', name: 'Birthday Party', emoji: '🎉', color: 'pink' },
  { id: 'wedding-planning', name: 'Wedding Planning', emoji: '👰', color: 'white' },
  { id: 'baby-shower', name: 'Baby Shower', emoji: '👶', color: 'yellow' },
  { id: 'bridal-shower', name: 'Bridal Shower', emoji: '💍', color: 'rose' },
  { id: 'engagement', name: 'Engagement Party', emoji: '💎', color: 'purple' },
  { id: 'anniversary-party', name: 'Anniversary Party', emoji: '💕', color: 'rose' },
  { id: 'graduation', name: 'Graduation Party', emoji: '🎓', color: 'blue' },
  { id: 'prom', name: 'Prom Night', emoji: '💃', color: 'fuchsia' },
  { id: 'homecoming', name: 'Homecoming', emoji: '🏫', color: 'red' },
  { id: 'reunion-party', name: 'Reunion Party', emoji: '🎊', color: 'amber' },
  { id: 'farewell', name: 'Farewell Party', emoji: '👋', color: 'blue' },
  { id: 'welcome-party', name: 'Welcome Party', emoji: '🎈', color: 'pink' },
  { id: 'housewarming', name: 'Housewarming', emoji: '🏠', color: 'orange' },
  { id: 'dinner-party', name: 'Dinner Party', emoji: '🍽️', color: 'red' },
  { id: 'cocktail-party', name: 'Cocktail Party', emoji: '🍸', color: 'amber' },
  { id: 'tea-party', name: 'Tea Party', emoji: '🍵', color: 'green' },
  { id: 'garden-party', name: 'Garden Party', emoji: '🌷', color: 'green' },
  { id: 'pool-party', name: 'Pool Party', emoji: '🏊‍♀️', color: 'sky' },
  { id: 'bbq', name: 'BBQ & Grill', emoji: '🍖', color: 'red' },
  { id: 'picnic', name: 'Picnic', emoji: '🧺', color: 'green' },
  { id: 'beach-party', name: 'Beach Party', emoji: '🏖️', color: 'sky' },
  { id: 'boat-party', name: 'Boat Party', emoji: '⛵', color: 'blue' },
  { id: 'camping-trip', name: 'Camping Trip', emoji: '🏕️', color: 'green' },
  { id: 'road-trip', name: 'Road Trip', emoji: '🚗', color: 'blue' },
  { id: 'vacation', name: 'Vacation Plans', emoji: '✈️', color: 'sky' },
  { id: 'staycation', name: 'Staycation', emoji: '🏡', color: 'teal' },
  { id: 'day-trip', name: 'Day Trip', emoji: '🗺️', color: 'green' },
  { id: 'weekend-getaway', name: 'Weekend Getaway', emoji: '🌄', color: 'orange' },
  { id: 'international-travel', name: 'International Travel', emoji: '🌍', color: 'blue' },
  { id: 'domestic-travel', name: 'Domestic Travel', emoji: '🗺️', color: 'green' },
  { id: 'business-travel', name: 'Business Travel', emoji: '💼', color: 'slate' },
  { id: 'solo-travel', name: 'Solo Travel', emoji: '🧳', color: 'purple' },
  { id: 'group-travel', name: 'Group Travel', emoji: '👥', color: 'teal' },
  { id: 'family-vacation', name: 'Family Vacation', emoji: '👨‍👩‍👧', color: 'orange' },
  { id: 'couples-trip', name: 'Couples Trip', emoji: '💑', color: 'rose' },
  { id: 'friend-trip', name: 'Friends Trip', emoji: '👯‍♀️', color: 'fuchsia' },
  { id: 'honeymoon', name: 'Honeymoon', emoji: '💕', color: 'rose' },
  { id: 'babymoon', name: 'Babymoon', emoji: '👶', color: 'yellow' },
  { id: 'spring-break', name: 'Spring Break', emoji: '🌸', color: 'pink' },
  { id: 'summer-vacation', name: 'Summer Vacation', emoji: '☀️', color: 'yellow' },
  { id: 'winter-vacation', name: 'Winter Vacation', emoji: '❄️', color: 'sky' },
  { id: 'fall-vacation', name: 'Fall Vacation', emoji: '🍂', color: 'orange' },
  { id: 'ski-trip', name: 'Ski Trip', emoji: '⛷️', color: 'sky' },
  { id: 'beach-vacation', name: 'Beach Vacation', emoji: '🏖️', color: 'sky' },
  { id: 'mountain-vacation', name: 'Mountain Vacation', emoji: '⛰️', color: 'emerald' },
  { id: 'city-break', name: 'City Break', emoji: '🏙️', color: 'slate' },
  { id: 'countryside', name: 'Countryside Retreat', emoji: '🌾', color: 'green' },
  { id: 'island-getaway', name: 'Island Getaway', emoji: '🏝️', color: 'sky' },
  { id: 'cruise', name: 'Cruise Trip', emoji: '🚢', color: 'blue' },
  { id: 'resort', name: 'Resort Stay', emoji: '🏨', color: 'amber' },
  { id: 'hotel', name: 'Hotel Stay', emoji: '🛏️', color: 'purple' },
  { id: 'airbnb', name: 'Airbnb Stay', emoji: '🏠', color: 'pink' },
  { id: 'hostel', name: 'Hostel Stay', emoji: '🎒', color: 'orange' },
  { id: 'glamping', name: 'Glamping', emoji: '⛺', color: 'green' },
  { id: 'rv-trip', name: 'RV Trip', emoji: '🚐', color: 'blue' },
  { id: 'vanlife', name: 'Van Life', emoji: '🚐', color: 'orange' },
  { id: 'backpacking', name: 'Backpacking', emoji: '🎒', color: 'green' },
  { id: 'hiking-trip', name: 'Hiking Trip', emoji: '🥾', color: 'emerald' },
  { id: 'trekking', name: 'Trekking', emoji: '🏔️', color: 'slate' },
  { id: 'climbing', name: 'Rock Climbing', emoji: '🧗', color: 'red' },
  { id: 'bouldering', name: 'Bouldering', emoji: '🪨', color: 'stone' },
  { id: 'caving', name: 'Caving & Spelunking', emoji: '🦇', color: 'slate' },
  { id: 'zip-lining', name: 'Zip Lining', emoji: '🪂', color: 'orange' },
  { id: 'skydiving', name: 'Skydiving', emoji: '🪂', color: 'sky' },
  { id: 'bungee', name: 'Bungee Jumping', emoji: '🪢', color: 'red' },
  { id: 'paragliding', name: 'Paragliding', emoji: '🪂', color: 'sky' },
  { id: 'hot-air-balloon', name: 'Hot Air Balloon', emoji: '🎈', color: 'pink' },
  { id: 'helicopter', name: 'Helicopter Ride', emoji: '🚁', color: 'slate' },
  { id: 'small-plane', name: 'Small Plane Ride', emoji: '✈️', color: 'sky' },
  { id: 'scuba', name: 'Scuba Diving', emoji: '🤿', color: 'blue' },
  { id: 'snorkeling', name: 'Snorkeling', emoji: '🐠', color: 'cyan' },
  { id: 'surfing', name: 'Surfing', emoji: '🏄‍♀️', color: 'sky' },
  { id: 'kitesurfing', name: 'Kitesurfing', emoji: '🪁', color: 'blue' },
  { id: 'windsurfing', name: 'Windsurfing', emoji: '⛵', color: 'sky' },
  { id: 'paddleboarding', name: 'Paddleboarding', emoji: '🏄‍♀️', color: 'blue' },
  { id: 'kayaking', name: 'Kayaking', emoji: '🛶', color: 'blue' },
  { id: 'canoeing', name: 'Canoeing', emoji: '🛶', color: 'green' },
  { id: 'rafting', name: 'White Water Rafting', emoji: '🚣', color: 'blue' },
  { id: 'sailing', name: 'Sailing', emoji: '⛵', color: 'sky' },
  { id: 'fishing', name: 'Fishing', emoji: '🎣', color: 'blue' },
  { id: 'hunting', name: 'Hunting', emoji: '🏹', color: 'green' },
  { id: 'horseback', name: 'Horseback Riding', emoji: '🐴', color: 'brown' },
  { id: 'camel-ride', name: 'Camel Ride', emoji: '🐫', color: 'amber' },
  { id: 'elephant-ride', name: 'Elephant Ride', emoji: '🐘', color: 'gray' },
  { id: 'safari', name: 'Safari', emoji: '🦁', color: 'amber' },
  { id: 'zoo', name: 'Zoo Visit', emoji: '🦒', color: 'green' },
  { id: 'aquarium', name: 'Aquarium Visit', emoji: '🐠', color: 'blue' },
  { id: 'botanical-garden', name: 'Botanical Garden', emoji: '🌺', color: 'green' },
  { id: 'national-park', name: 'National Park', emoji: '🏞️', color: 'green' },
  { id: 'state-park', name: 'State Park', emoji: '🌲', color: 'green' },
  { id: 'amusement-park', name: 'Amusement Park', emoji: '🎢', color: 'red' },
  { id: 'water-park', name: 'Water Park', emoji: '💦', color: 'sky' },
  { id: 'theme-park', name: 'Theme Park', emoji: '🎡', color: 'pink' },
  { id: 'carnival', name: 'Carnival', emoji: '🎪', color: 'amber' },
  { id: 'fair', name: 'Fair & Festival', emoji: '🎡', color: 'orange' },
  { id: 'circus', name: 'Circus', emoji: '🎪', color: 'red' },
  { id: 'concert', name: 'Concerts', emoji: '🎤', color: 'purple' },
  { id: 'festival', name: 'Music Festivals', emoji: '🎶', color: 'pink' },
  { id: 'rave', name: 'Raves & EDM', emoji: '🎧', color: 'purple' },
  { id: 'club', name: 'Nightclubs', emoji: '🪩', color: 'fuchsia' },
  { id: 'bar', name: 'Bars & Lounges', emoji: '🍸', color: 'amber' },
  { id: 'pub', name: 'Pubs', emoji: '🍺', color: 'amber' },
  { id: 'brewery', name: 'Brewery Tours', emoji: '🍻', color: 'amber' },
  { id: 'winery', name: 'Winery Tours', emoji: '🍷', color: 'red' },
  { id: 'distillery', name: 'Distillery Tours', emoji: '🥃', color: 'amber' },
  { id: 'coffee-shop', name: 'Coffee Shops', emoji: '☕', color: 'brown' },
  { id: 'cafe', name: 'Cafés & Brunch', emoji: '🥐', color: 'amber' },
  { id: 'bakery', name: 'Bakeries', emoji: '🥖', color: 'amber' },
  { id: 'ice-cream', name: 'Ice Cream Shops', emoji: '🍦', color: 'pink' },
  { id: 'chocolate-shop', name: 'Chocolate Shops', emoji: '🍫', color: 'amber' },
  { id: 'candy-store', name: 'Candy Stores', emoji: '🍬', color: 'pink' },
  { id: 'bookstore', name: 'Bookstores', emoji: '📚', color: 'amber' },
  { id: 'library', name: 'Library Visits', emoji: '📖', color: 'blue' },
  { id: 'museum', name: 'Museums', emoji: '🏛️', color: 'stone' },
  { id: 'art-gallery', name: 'Art Galleries', emoji: '🖼️', color: 'purple' },
  { id: 'history-museum', name: 'History Museums', emoji: '🏛️', color: 'stone' },
  { id: 'science-museum', name: 'Science Museums', emoji: '🔬', color: 'blue' },
  { id: 'children-museum', name: "Children's Museums", emoji: '🧸', color: 'pink' },
  { id: 'planetarium', name: 'Planetarium', emoji: '🌌', color: 'indigo' },
  { id: 'observatory', name: 'Observatory', emoji: '🔭', color: 'indigo' },
  { id: 'zoo-aquarium', name: 'Zoo & Aquarium', emoji: '🐠', color: 'blue' },
  { id: 'botanical', name: 'Botanical Gardens', emoji: '🌺', color: 'green' },
  { id: 'arboretum', name: 'Arboretum', emoji: '🌳', color: 'green' },
  { id: 'park', name: 'Parks & Playgrounds', emoji: '🌳', color: 'green' },
  { id: 'playground', name: 'Playgrounds', emoji: '🛝', color: 'orange' },
  { id: 'dog-park', name: 'Dog Parks', emoji: '🐕', color: 'green' },
  { id: 'skate-park', name: 'Skate Parks', emoji: '🛹', color: 'slate' },
  { id: 'bmx-park', name: 'BMX Parks', emoji: '🚲', color: 'orange' },
  { id: 'tennis', name: 'Tennis', emoji: '🎾', color: 'green' },
  { id: 'basketball', name: 'Basketball', emoji: '🏀', color: 'orange' },
  { id: 'soccer', name: 'Soccer', emoji: '⚽', color: 'green' },
  { id: 'baseball', name: 'Baseball', emoji: '⚾', color: 'red' },
  { id: 'football', name: 'Football', emoji: '🏈', color: 'brown' },
  { id: 'volleyball', name: 'Volleyball', emoji: '🏐', color: 'yellow' },
  { id: 'badminton', name: 'Badminton', emoji: '🏸', color: 'green' },
  { id: 'table-tennis', name: 'Table Tennis', emoji: '🏓', color: 'red' },
  { id: 'golf', name: 'Golf', emoji: '⛳', color: 'green' },
  { id: 'mini-golf', name: 'Mini Golf', emoji: '⛳', color: 'pink' },
  { id: 'bowling', name: 'Bowling', emoji: '🎳', color: 'purple' },
  { id: 'billiards', name: 'Billiards & Pool', emoji: '🎱', color: 'green' },
  { id: 'darts', name: 'Darts', emoji: '🎯', color: 'red' },
  { id: 'archery', name: 'Archery', emoji: '🏹', color: 'green' },
  { id: 'fencing', name: 'Fencing', emoji: '🤺', color: 'slate' },
  { id: 'boxing', name: 'Boxing', emoji: '🥊', color: 'red' },
  { id: 'martial-arts', name: 'Martial Arts', emoji: '🥋', color: 'red' },
  { id: 'wrestling', name: 'Wrestling', emoji: '🤼', color: 'red' },
  { id: 'gymnastics', name: 'Gymnastics', emoji: '🤸', color: 'pink' },
  { id: 'cheerleading', name: 'Cheerleading', emoji: '📣', color: 'red' },
  { id: 'dance-team', name: 'Dance Team', emoji: '💃', color: 'fuchsia' },
  { id: 'marching-band', name: 'Marching Band', emoji: '🎺', color: 'blue' },
  { id: 'choir', name: 'Choir & Singing', emoji: '🎵', color: 'purple' },
  { id: 'orchestra', name: 'Orchestra', emoji: '🎻', color: 'amber' },
  { id: 'band', name: 'Band & Instruments', emoji: '🎸', color: 'red' },
  { id: 'dj', name: 'DJ & Music Production', emoji: '🎧', color: 'purple' },
  { id: 'music-production', name: 'Music Production', emoji: '🎹', color: 'indigo' },
  { id: 'recording', name: 'Recording Studio', emoji: '🎙️', color: 'slate' },
  { id: 'songwriting', name: 'Songwriting', emoji: '🎵', color: 'pink' },
  { id: 'composing', name: 'Composing', emoji: '🎼', color: 'purple' },
  { id: 'film', name: 'Filmmaking', emoji: '🎬', color: 'red' },
  { id: 'photography-shoot', name: 'Photography Shoots', emoji: '📸', color: 'cyan' },
  { id: 'videography', name: 'Videography', emoji: '🎥', color: 'slate' },
  { id: 'editing', name: 'Video Editing', emoji: '✂️', color: 'blue' },
  { id: 'animation', name: 'Animation', emoji: '🎨', color: 'violet' },
  { id: 'graphic-design', name: 'Graphic Design', emoji: '🎨', color: 'pink' },
  { id: 'illustration', name: 'Illustration', emoji: '🖍️', color: 'amber' },
  { id: 'painting', name: 'Painting', emoji: '🎨', color: 'blue' },
  { id: 'drawing', name: 'Drawing & Sketching', emoji: '✏️', color: 'stone' },
  { id: 'sculpture', name: 'Sculpture', emoji: '🗿', color: 'stone' },
  { id: 'pottery', name: 'Pottery & Ceramics', emoji: '🏺', color: 'amber' },
  { id: 'printmaking', name: 'Printmaking', emoji: '🖨️', color: 'slate' },
  { id: 'textile-art', name: 'Textile Art', emoji: '🧵', color: 'pink' },
  { id: 'fiber-art', name: 'Fiber Art', emoji: '🧶', color: 'purple' },
  { id: 'jewelry-making', name: 'Jewelry Making', emoji: '💍', color: 'amber' },
  { id: 'woodworking', name: 'Woodworking', emoji: '🪵', color: 'brown' },
  { id: 'metalworking', name: 'Metalworking', emoji: '⚒️', color: 'slate' },
  { id: 'glassblowing', name: 'Glassblowing', emoji: '🔥', color: 'orange' },
  { id: 'leather-craft', name: 'Leather Craft', emoji: '👜', color: 'brown' },
  { id: 'paper-craft', name: 'Paper Craft', emoji: '📄', color: 'white' },
  { id: 'origami', name: 'Origami', emoji: '🦢', color: 'pink' },
  { id: 'calligraphy', name: 'Calligraphy', emoji: '🖋️', color: 'purple' },
  { id: 'bookbinding', name: 'Bookbinding', emoji: '📔', color: 'amber' },
  { id: 'scrapbooking', name: 'Scrapbooking', emoji: '📒', color: 'pink' },
  { id: 'card-making', name: 'Card Making', emoji: '💌', color: 'rose' },
  { id: 'gift-wrapping', name: 'Gift Wrapping', emoji: '🎁', color: 'pink' },
  { id: 'flower-arranging', name: 'Flower Arranging', emoji: '💐', color: 'rose' },
  { id: 'wreath-making', name: 'Wreath Making', emoji: '🎀', color: 'green' },
  { id: 'candle-making', name: 'Candle Making', emoji: '🕯️', color: 'amber' },
  { id: 'soap-making', name: 'Soap Making', emoji: '🧼', color: 'blue' },
  { id: 'bath-bombs', name: 'Bath Bombs', emoji: '🛁', color: 'pink' },
  { id: 'lipstick-making', name: 'Lipstick Making', emoji: '💄', color: 'rose' },
  { id: 'perfume-making', name: 'Perfume Making', emoji: '🌸', color: 'pink' },
  { id: 'skincare-making', name: 'Skincare Making', emoji: '🧴', color: 'cyan' },
  { id: 'hair-products', name: 'Hair Products DIY', emoji: '💇‍♀️', color: 'purple' },
  { id: 'cleaning-products', name: 'Cleaning Products DIY', emoji: '🧹', color: 'blue' },
  { id: 'candle-business', name: 'Candle Business', emoji: '🕯️', color: 'amber' },
  { id: 'soap-business', name: 'Soap Business', emoji: '🧼', color: 'blue' },
  { id: 'bakery-business', name: 'Bakery Business', emoji: '🧁', color: 'pink' },
  { id: 'catering', name: 'Catering Business', emoji: '🍽️', color: 'red' },
  { id: 'food-truck', name: 'Food Truck', emoji: '🚚', color: 'orange' },
  { id: 'restaurant-business', name: 'Restaurant Business', emoji: '🍜', color: 'red' },
  { id: 'cafe-business', name: 'Café Business', emoji: '☕', color: 'brown' },
  { id: 'bar-business', name: 'Bar Business', emoji: '🍸', color: 'amber' },
  { id: 'brewery-business', name: 'Brewery Business', emoji: '🍺', color: 'amber' },
  { id: 'winery-business', name: 'Winery Business', emoji: '🍷', color: 'red' },
  { id: 'distillery-business', name: 'Distillery Business', emoji: '🥃', color: 'amber' },
  { id: 'farm-business', name: 'Farm Business', emoji: '🌾', color: 'green' },
  { id: 'florist-business', name: 'Florist Business', emoji: '💐', color: 'rose' },
  { id: 'landscaping', name: 'Landscaping Business', emoji: '🌳', color: 'green' },
  { id: 'gardening-business', name: 'Gardening Business', emoji: '🌱', color: 'green' },
  { id: 'nursery', name: 'Plant Nursery', emoji: '🌿', color: 'green' },
  { id: 'pet-business', name: 'Pet Business', emoji: '🐾', color: 'orange' },
  { id: 'pet-grooming', name: 'Pet Grooming', emoji: '🐕', color: 'pink' },
  { id: 'pet-sitting', name: 'Pet Sitting', emoji: '🐶', color: 'orange' },
  { id: 'dog-walking', name: 'Dog Walking', emoji: '🐕', color: 'green' },
  { id: 'vet-clinic', name: 'Vet Clinic', emoji: '🏥', color: 'blue' },
  { id: 'animal-shelter', name: 'Animal Shelter', emoji: '🏠', color: 'orange' },
  { id: 'animal-rescue', name: 'Animal Rescue', emoji: '🐾', color: 'pink' },
  { id: 'wildlife-rescue', name: 'Wildlife Rescue', emoji: '🦅', color: 'green' },
  { id: 'marine-biology', name: 'Marine Biology', emoji: '🐋', color: 'blue' },
  { id: 'veterinary', name: 'Veterinary Studies', emoji: '🐾', color: 'blue' },
  { id: 'animal-training', name: 'Animal Training', emoji: '🐕', color: 'orange' },
  { id: 'horse-training', name: 'Horse Training', emoji: '🐴', color: 'brown' },
  { id: 'dog-training', name: 'Dog Training', emoji: '🐶', color: 'orange' },
  { id: 'cat-behavior', name: 'Cat Behavior', emoji: '🐱', color: 'pink' },
  { id: 'bird-watching', name: 'Bird Watching', emoji: '🐦', color: 'green' },
  { id: 'bird-feeding', name: 'Bird Feeding', emoji: '🐦', color: 'yellow' },
  { id: 'beekeeping', name: 'Beekeeping', emoji: '🐝', color: 'yellow' },
  { id: 'butterfly-garden', name: 'Butterfly Garden', emoji: '🦋', color: 'pink' },
  { id: 'worm-composting', name: 'Worm Composting', emoji: '🪱', color: 'brown' },
  { id: 'composting', name: 'Composting', emoji: '🍂', color: 'brown' },
  { id: 'recycling', name: 'Recycling', emoji: '♻️', color: 'green' },
  { id: 'upcycling', name: 'Upcycling', emoji: '♻️', color: 'teal' },
  { id: 'zero-waste', name: 'Zero Waste', emoji: '🌍', color: 'green' },
  { id: 'sustainable-living', name: 'Sustainable Living', emoji: '🌱', color: 'green' },
  { id: 'eco-friendly', name: 'Eco-Friendly', emoji: '🌿', color: 'green' },
  { id: 'green-living', name: 'Green Living', emoji: '🌍', color: 'green' },
  { id: 'minimalism-living', name: 'Minimalist Living', emoji: '🧘', color: 'stone' },
  { id: 'tiny-house', name: 'Tiny House', emoji: '🏠', color: 'brown' },
  { id: 'off-grid', name: 'Off-Grid Living', emoji: '⚡', color: 'yellow' },
  { id: 'homesteading', name: 'Homesteading', emoji: '🌾', color: 'green' },
  { id: 'permaculture', name: 'Permaculture', emoji: '🌱', color: 'green' },
  { id: 'organic-gardening', name: 'Organic Gardening', emoji: '🥕', color: 'orange' },
  { id: 'hydroponics', name: 'Hydroponics', emoji: '💧', color: 'blue' },
  { id: 'aquaponics', name: 'Aquaponics', emoji: '🐟', color: 'blue' },
  { id: 'vertical-garden', name: 'Vertical Garden', emoji: '🌿', color: 'green' },
  { id: 'rooftop-garden', name: 'Rooftop Garden', emoji: '🏙️', color: 'green' },
  { id: 'indoor-garden', name: 'Indoor Garden', emoji: '🪴', color: 'green' },
  { id: 'succulent', name: 'Succulents', emoji: '🌵', color: 'green' },
  { id: 'cactus', name: 'Cacti', emoji: '🌵', color: 'green' },
  { id: 'bonsai', name: 'Bonsai', emoji: '🌳', color: 'green' },
  { id: 'orchid', name: 'Orchids', emoji: '🌸', color: 'pink' },
  { id: 'rose-garden', name: 'Rose Garden', emoji: '🌹', color: 'red' },
  { id: 'herb-garden', name: 'Herb Garden', emoji: '🌿', color: 'green' },
  { id: 'vegetable-garden', name: 'Vegetable Garden', emoji: '🥬', color: 'green' },
  { id: 'fruit-garden', name: 'Fruit Garden', emoji: '🍎', color: 'red' },
  { id: 'flower-garden', name: 'Flower Garden', emoji: '🌷', color: 'pink' },
  { id: 'wildflower', name: 'Wildflowers', emoji: '🌼', color: 'yellow' },
  { id: 'pollinator-garden', name: 'Pollinator Garden', emoji: '🐝', color: 'yellow' },
  { id: 'native-plants', name: 'Native Plants', emoji: '🌿', color: 'green' },
  { id: 'medicinal-herbs', name: 'Medicinal Herbs', emoji: '🌿', color: 'green' },
  { id: 'aromatic-herbs', name: 'Aromatic Herbs', emoji: '🌿', color: 'purple' },
  { id: 'culinary-herbs', name: 'Culinary Herbs', emoji: '🌿', color: 'green' },
  { id: 'spice-garden', name: 'Spice Garden', emoji: '🌶️', color: 'red' },
  { id: 'tea-garden', name: 'Tea Garden', emoji: '🍵', color: 'green' },
  { id: 'coffee-garden', name: 'Coffee Garden', emoji: '☕', color: 'brown' },
  { id: 'chocolate-garden', name: 'Chocolate Garden', emoji: '🍫', color: 'brown' },
  { id: 'vanilla-garden', name: 'Vanilla Garden', emoji: '🌿', color: 'yellow' },
  { id: 'saffron-garden', name: 'Saffron Garden', emoji: '🌸', color: 'red' },
  { id: 'lavender-garden', name: 'Lavender Garden', emoji: '💜', color: 'purple' },
  { id: 'chamomile-garden', name: 'Chamomile Garden', emoji: '🌼', color: 'yellow' },
  { id: 'peppermint-garden', name: 'Peppermint Garden', emoji: '🌿', color: 'green' },
  { id: 'lemon-balm', name: 'Lemon Balm', emoji: '🍋', color: 'yellow' },
  { id: 'rosemary-garden', name: 'Rosemary Garden', emoji: '🌿', color: 'green' },
  { id: 'thyme-garden', name: 'Thyme Garden', emoji: '🌿', color: 'green' },
  { id: 'sage-garden', name: 'Sage Garden', emoji: '🌿', color: 'green' },
  { id: 'oregano-garden', name: 'Oregano Garden', emoji: '🌿', color: 'green' },
  { id: 'basil-garden', name: 'Basil Garden', emoji: '🌿', color: 'green' },
  { id: 'cilantro-garden', name: 'Cilantro Garden', emoji: '🌿', color: 'green' },
  { id: 'parsley-garden', name: 'Parsley Garden', emoji: '🌿', color: 'green' },
  { id: 'dill-garden', name: 'Dill Garden', emoji: '🌿', color: 'green' },
  { id: 'mint-garden', name: 'Mint Garden', emoji: '🌿', color: 'green' },
  { id: 'lemongrass', name: 'Lemongrass', emoji: '🌿', color: 'yellow' },
  { id: 'ginger-garden', name: 'Ginger Garden', emoji: '🫚', color: 'yellow' },
  { id: 'turmeric-garden', name: 'Turmeric Garden', emoji: '🫚', color: 'yellow' },
  { id: 'garlic-garden', name: 'Garlic Garden', emoji: '🧄', color: 'white' },
  { id: 'onion-garden', name: 'Onion Garden', emoji: '🧅', color: 'white' },
  { id: 'tomato-garden', name: 'Tomato Garden', emoji: '🍅', color: 'red' },
  { id: 'pepper-garden', name: 'Pepper Garden', emoji: '🌶️', color: 'red' },
  { id: 'cucumber-garden', name: 'Cucumber Garden', emoji: '🥒', color: 'green' },
  { id: 'lettuce-garden', name: 'Lettuce Garden', emoji: '🥬', color: 'green' },
  { id: 'spinach-garden', name: 'Spinach Garden', emoji: '🥬', color: 'green' },
  { id: 'kale-garden', name: 'Kale Garden', emoji: '🥬', color: 'green' },
  { id: 'broccoli-garden', name: 'Broccoli Garden', emoji: '🥦', color: 'green' },
  { id: 'cauliflower-garden', name: 'Cauliflower Garden', emoji: '🥦', color: 'white' },
  { id: 'cabbage-garden', name: 'Cabbage Garden', emoji: '🥬', color: 'green' },
  { id: 'brussels-sprouts', name: 'Brussels Sprouts', emoji: '🥬', color: 'green' },
  { id: 'asparagus-garden', name: 'Asparagus Garden', emoji: '🌿', color: 'green' },
  { id: 'celery-garden', name: 'Celery Garden', emoji: '🌿', color: 'green' },
  { id: 'carrot-garden', name: 'Carrot Garden', emoji: '🥕', color: 'orange' },
  { id: 'potato-garden', name: 'Potato Garden', emoji: '🥔', color: 'brown' },
  { id: 'sweet-potato', name: 'Sweet Potato', emoji: '🍠', color: 'orange' },
  { id: 'corn-garden', name: 'Corn Garden', emoji: '🌽', color: 'yellow' },
  { id: 'bean-garden', name: 'Bean Garden', emoji: '🫘', color: 'green' },
  { id: 'pea-garden', name: 'Pea Garden', emoji: '🫛', color: 'green' },
  { id: 'lentil-garden', name: 'Lentil Garden', emoji: '🫘', color: 'brown' },
  { id: 'chickpea-garden', name: 'Chickpea Garden', emoji: '🫘', color: 'yellow' },
  { id: 'soybean-garden', name: 'Soybean Garden', emoji: '🫘', color: 'green' },
  { id: 'tofu-making', name: 'Tofu Making', emoji: '🧊', color: 'white' },
  { id: 'tempeh-making', name: 'Tempeh Making', emoji: '🫘', color: 'brown' },
  { id: 'seitan-making', name: 'Seitan Making', emoji: '🌾', color: 'brown' },
  { id: 'plant-based-milk', name: 'Plant-Based Milk', emoji: '🥛', color: 'white' },
  { id: 'almond-milk', name: 'Almond Milk', emoji: '🥛', color: 'white' },
  { id: 'oat-milk', name: 'Oat Milk', emoji: '🥛', color: 'white' },
  { id: 'soy-milk', name: 'Soy Milk', emoji: '🥛', color: 'white' },
  { id: 'coconut-milk', name: 'Coconut Milk', emoji: '🥛', color: 'white' },
  { id: 'rice-milk', name: 'Rice Milk', emoji: '🥛', color: 'white' },
  { id: 'cashew-milk', name: 'Cashew Milk', emoji: '🥛', color: 'white' },
  { id: 'hemp-milk', name: 'Hemp Milk', emoji: '🥛', color: 'green' },
  { id: 'flax-milk', name: 'Flax Milk', emoji: '🥛', color: 'yellow' },
  { id: 'pea-milk', name: 'Pea Milk', emoji: '🥛', color: 'green' },
  { id: 'macadamia-milk', name: 'Macadamia Milk', emoji: '🥛', color: 'white' },
  { id: 'hazelnut-milk', name: 'Hazelnut Milk', emoji: '🥛', color: 'brown' },
  { id: 'walnut-milk', name: 'Walnut Milk', emoji: '🥛', color: 'brown' },
  { id: 'pistachio-milk', name: 'Pistachio Milk', emoji: '🥛', color: 'green' },
  { id: 'brazil-nut-milk', name: 'Brazil Nut Milk', emoji: '🥛', color: 'brown' },
  { id: 'pecan-milk', name: 'Pecan Milk', emoji: '🥛', color: 'brown' },
  { id: 'pine-nut-milk', name: 'Pine Nut Milk', emoji: '🥛', color: 'white' },
  { id: 'chestnut-milk', name: 'Chestnut Milk', emoji: '🥛', color: 'brown' },
  { id: 'acorn-milk', name: 'Acorn Milk', emoji: '🥛', color: 'brown' },
  { id: 'tigernut-milk', name: 'Tigernut Milk', emoji: '🥛', color: 'brown' },
  { id: 'banana-milk', name: 'Banana Milk', emoji: '🍌', color: 'yellow' },
  { id: 'apple-milk', name: 'Apple Milk', emoji: '🍎', color: 'red' },
  { id: 'pear-milk', name: 'Pear Milk', emoji: '🍐', color: 'green' },
  { id: 'peach-milk', name: 'Peach Milk', emoji: '🍑', color: 'pink' },
  { id: 'plum-milk', name: 'Plum Milk', emoji: '🫐', color: 'purple' },
  { id: 'apricot-milk', name: 'Apricot Milk', emoji: '🍑', color: 'orange' },
  { id: 'cherry-milk', name: 'Cherry Milk', emoji: '🍒', color: 'red' },
  { id: 'strawberry-milk', name: 'Strawberry Milk', emoji: '🍓', color: 'pink' },
  { id: 'raspberry-milk', name: 'Raspberry Milk', emoji: '🍇', color: 'red' },
  { id: 'blueberry-milk', name: 'Blueberry Milk', emoji: '🫐', color: 'blue' },
  { id: 'blackberry-milk', name: 'Blackberry Milk', emoji: '🫐', color: 'purple' },
  { id: 'cranberry-milk', name: 'Cranberry Milk', emoji: '🍒', color: 'red' },
  { id: 'gooseberry-milk', name: 'Gooseberry Milk', emoji: '🍇', color: 'green' },
  { id: 'currant-milk', name: 'Currant Milk', emoji: '🍇', color: 'red' },
  { id: 'elderberry-milk', name: 'Elderberry Milk', emoji: '🫐', color: 'purple' },
  { id: 'mulberry-milk', name: 'Mulberry Milk', emoji: '🫐', color: 'purple' },
  { id: 'boysenberry-milk', name: 'Boysenberry Milk', emoji: '🫐', color: 'purple' },
  { id: 'loganberry-milk', name: 'Loganberry Milk', emoji: '🫐', color: 'red' },
  { id: 'marionberry-milk', name: 'Marionberry Milk', emoji: '🫐', color: 'purple' },
  { id: 'olallieberry-milk', name: 'Olallieberry Milk', emoji: '🫐', color: 'purple' },
  { id: 'cloudberry-milk', name: 'Cloudberry Milk', emoji: '🫐', color: 'orange' },
  { id: 'lingonberry-milk', name: 'Lingonberry Milk', emoji: '🍒', color: 'red' },
  { id: 'huckleberry-milk', name: 'Huckleberry Milk', emoji: '🫐', color: 'blue' },
  { id: 'salmonberry-milk', name: 'Salmonberry Milk', emoji: '🫐', color: 'orange' },
  { id: 'thimbleberry-milk', name: 'Thimbleberry Milk', emoji: '🫐', color: 'red' },
  { id: 'wineberry-milk', name: 'Wineberry Milk', emoji: '🫐', color: 'red' },
  { id: 'dewberry-milk', name: 'Dewberry Milk', emoji: '🫐', color: 'blue' },
  { id: 'youngberry-milk', name: 'Youngberry Milk', emoji: '🫐', color: 'purple' },
  { id: 'tayberry-milk', name: 'Tayberry Milk', emoji: '🫐', color: 'red' },
  { id: 'tummelberry-milk', name: 'Tummelberry Milk', emoji: '🫐', color: 'red' },
  { id: 'veitchberry-milk', name: 'Veitchberry Milk', emoji: '🫐', color: 'red' },
  { id: 'skovboeberry-milk', name: 'Skovboeberry Milk', emoji: '🫐', color: 'red' },
  { id: 'kotata-berry-milk', name: 'Kotata Berry Milk', emoji: '🫐', color: 'red' },
  { id: 'silverberry-milk', name: 'Silverberry Milk', emoji: '🫐', color: 'silver' },
  { id: 'buffaloberry-milk', name: 'Buffaloberry Milk', emoji: '🫐', color: 'red' },
  { id: 'sea-buckthorn-milk', name: 'Sea Buckthorn Milk', emoji: '🫐', color: 'orange' },
  { id: 'goji-berry-milk', name: 'Goji Berry Milk', emoji: '🫐', color: 'red' },
  { id: 'acai-berry-milk', name: 'Acai Berry Milk', emoji: '🫐', color: 'purple' },
  { id: 'maqui-berry-milk', name: 'Maqui Berry Milk', emoji: '🫐', color: 'purple' },
  { id: 'camu-camu-milk', name: 'Camu Camu Milk', emoji: '🫐', color: 'red' },
  { id: 'acerola-milk', name: 'Acerola Milk', emoji: '🫐', color: 'red' },
  { id: 'amla-milk', name: 'Amla Milk', emoji: '🫐', color: 'green' },
  { id: 'baobab-milk', name: 'Baobab Milk', emoji: '🫐', color: 'brown' },
  { id: 'marula-milk', name: 'Marula Milk', emoji: '🫐', color: 'yellow' },
  { id: 'mongongo-milk', name: 'Mongongo Milk', emoji: '🫐', color: 'brown' },
  { id: 'safou-milk', name: 'Safou Milk', emoji: '🫐', color: 'blue' },
  { id: 'breadfruit-milk', name: 'Breadfruit Milk', emoji: '🫐', color: 'green' },
  { id: 'jackfruit-milk', name: 'Jackfruit Milk', emoji: '🫐', color: 'yellow' },
  { id: 'durian-milk', name: 'Durian Milk', emoji: '🫐', color: 'yellow' },
  { id: 'mangosteen-milk', name: 'Mangosteen Milk', emoji: '🫐', color: 'purple' },
  { id: 'rambutan-milk', name: 'Rambutan Milk', emoji: '🫐', color: 'red' },
  { id: 'lychee-milk', name: 'Lychee Milk', emoji: '🫐', color: 'pink' },
  { id: 'longan-milk', name: 'Longan Milk', emoji: '🫐', color: 'brown' },
  { id: 'guava-milk', name: 'Guava Milk', emoji: '🫐', color: 'pink' },
  { id: 'papaya-milk', name: 'Papaya Milk', emoji: '🫐', color: 'orange' },
  { id: 'passion-fruit-milk', name: 'Passion Fruit Milk', emoji: '🫐', color: 'yellow' },
  { id: 'dragon-fruit-milk', name: 'Dragon Fruit Milk', emoji: '🫐', color: 'pink' },
  { id: 'star-fruit-milk', name: 'Star Fruit Milk', emoji: '🫐', color: 'yellow' },
  { id: 'carambola-milk', name: 'Carambola Milk', emoji: '🫐', color: 'yellow' },
  { id: 'kumquat-milk', name: 'Kumquat Milk', emoji: '🫐', color: 'orange' },
  { id: 'loquat-milk', name: 'Loquat Milk', emoji: '🫐', color: 'orange' },
  { id: 'persimmon-milk', name: 'Persimmon Milk', emoji: '🫐', color: 'orange' },
  { id: 'pomegranate-milk', name: 'Pomegranate Milk', emoji: '🫐', color: 'red' },
  { id: 'fig-milk', name: 'Fig Milk', emoji: '🫐', color: 'purple' },
  { id: 'date-fruit-milk', name: 'Date Fruit Milk', emoji: '🫐', color: 'brown' },
  { id: 'olive-milk', name: 'Olive Milk', emoji: '🫐', color: 'green' },
  { id: 'avocado-milk', name: 'Avocado Milk', emoji: '🫐', color: 'green' },
  { id: 'coconut-cream', name: 'Coconut Cream', emoji: '🥥', color: 'white' },
  { id: 'coconut-yogurt', name: 'Coconut Yogurt', emoji: '🥥', color: 'white' },
  { id: 'coconut-cheese', name: 'Coconut Cheese', emoji: '🧀', color: 'white' },
  { id: 'coconut-butter', name: 'Coconut Butter', emoji: '🧈', color: 'white' },
  { id: 'coconut-oil', name: 'Coconut Oil', emoji: '🥥', color: 'white' },
  { id: 'coconut-sugar', name: 'Coconut Sugar', emoji: '🥥', color: 'brown' },
  { id: 'coconut-flour', name: 'Coconut Flour', emoji: '🥥', color: 'white' },
  { id: 'coconut-milk-powder', name: 'Coconut Milk Powder', emoji: '🥥', color: 'white' },
  { id: 'coconut-cream-powder', name: 'Coconut Cream Powder', emoji: '🥥', color: 'white' },
  { id: 'coconut-water', name: 'Coconut Water', emoji: '🥥', color: 'clear' },
  { id: 'coconut-vinegar', name: 'Coconut Vinegar', emoji: '🥥', color: 'clear' },
  { id: 'coconut-aminos', name: 'Coconut Aminos', emoji: '🥥', color: 'brown' },
  { id: 'coconut-nectar', name: 'Coconut Nectar', emoji: '🥥', color: 'brown' },
  { id: 'coconut-syrup', name: 'Coconut Syrup', emoji: '🥥', color: 'brown' },
  { id: 'coconut-molasses', name: 'Coconut Molasses', emoji: '🥥', color: 'brown' },
  { id: 'coconut-honey', name: 'Coconut Honey', emoji: '🥥', color: 'yellow' },
  { id: 'coconut-jam', name: 'Coconut Jam', emoji: '🥥', color: 'brown' },
  { id: 'coconut-preserves', name: 'Coconut Preserves', emoji: '🥥', color: 'brown' },
  { id: 'coconut-chutney', name: 'Coconut Chutney', emoji: '🥥', color: 'green' },
  { id: 'coconut-relish', name: 'Coconut Relish', emoji: '🥥', color: 'green' },
  { id: 'coconut-salsa', name: 'Coconut Salsa', emoji: '🥥', color: 'red' },
  { id: 'coconut-guacamole', name: 'Coconut Guacamole', emoji: '🥥', color: 'green' },
  { id: 'coconut-hummus', name: 'Coconut Hummus', emoji: '🥥', color: 'beige' },
  { id: 'coconut-dip', name: 'Coconut Dip', emoji: '🥥', color: 'white' },
  { id: 'coconut-spread', name: 'Coconut Spread', emoji: '🥥', color: 'white' },
  { id: 'coconut-butter-milk', name: 'Coconut Butter Milk', emoji: '🥥', color: 'white' },
  { id: 'coconut-kefir', name: 'Coconut Kefir', emoji: '🥥', color: 'white' },
  { id: 'coconut-kombucha', name: 'Coconut Kombucha', emoji: '🥥', color: 'brown' },
  { id: 'coconut-water-kefir', name: 'Coconut Water Kefir', emoji: '🥥', color: 'clear' },
  { id: 'coconut-yogurt-drink', name: 'Coconut Yogurt Drink', emoji: '🥥', color: 'white' },
  { id: 'coconut-smoothie', name: 'Coconut Smoothie', emoji: '🥥', color: 'white' },
  { id: 'coconut-milkshake', name: 'Coconut Milkshake', emoji: '🥥', color: 'white' },
  { id: 'coconut-ice-cream', name: 'Coconut Ice Cream', emoji: '🥥', color: 'white' },
  { id: 'coconut-sorbet', name: 'Coconut Sorbet', emoji: '🥥', color: 'white' },
  { id: 'coconut-frozen-yogurt', name: 'Coconut Frozen Yogurt', emoji: '🥥', color: 'white' },
  { id: 'coconut-popsicle', name: 'Coconut Popsicle', emoji: '🥥', color: 'white' },
  { id: 'coconut-pudding', name: 'Coconut Pudding', emoji: '🥥', color: 'white' },
  { id: 'coconut-mousse', name: 'Coconut Mousse', emoji: '🥥', color: 'white' },
  { id: 'coconut-custard', name: 'Coconut Custard', emoji: '🥥', color: 'yellow' },
  { id: 'coconut-panna-cotta', name: 'Coconut Panna Cotta', emoji: '🥥', color: 'white' },
  { id: 'coconut-tapioca', name: 'Coconut Tapioca', emoji: '🥥', color: 'white' },
  { id: 'coconut-chia-pudding', name: 'Coconut Chia Pudding', emoji: '🥥', color: 'white' },
  { id: 'coconut-oatmeal', name: 'Coconut Oatmeal', emoji: '🥥', color: 'white' },
  { id: 'coconut-granola', name: 'Coconut Granola', emoji: '🥥', color: 'brown' },
  { id: 'coconut-cereal', name: 'Coconut Cereal', emoji: '🥥', color: 'white' },
  { id: 'coconut-porridge', name: 'Coconut Porridge', emoji: '🥥', color: 'white' },
  { id: 'coconut-congee', name: 'Coconut Congee', emoji: '🥥', color: 'white' },
  { id: 'coconut-rice', name: 'Coconut Rice', emoji: '🥥', color: 'white' },
  { id: 'coconut-fried-rice', name: 'Coconut Fried Rice', emoji: '🥥', color: 'yellow' },
  { id: 'coconut-rice-pudding', name: 'Coconut Rice Pudding', emoji: '🥥', color: 'white' },
  { id: 'coconut-sticky-rice', name: 'Coconut Sticky Rice', emoji: '🥥', color: 'white' },
  { id: 'coconut-mango-sticky-rice', name: 'Coconut Mango Sticky Rice', emoji: '🥥', color: 'yellow' },
  { id: 'coconut-bread', name: 'Coconut Bread', emoji: '🥥', color: 'brown' },
  { id: 'coconut-muffins', name: 'Coconut Muffins', emoji: '🥥', color: 'brown' },
  { id: 'coconut-cookies', name: 'Coconut Cookies', emoji: '🥥', color: 'brown' },
  { id: 'coconut-brownies', name: 'Coconut Brownies', emoji: '🥥', color: 'brown' },
  { id: 'coconut-cake', name: 'Coconut Cake', emoji: '🥥', color: 'white' },
  { id: 'coconut-cupcakes', name: 'Coconut Cupcakes', emoji: '🥥', color: 'white' },
  { id: 'coconut-pie', name: 'Coconut Pie', emoji: '🥥', color: 'white' },
  { id: 'coconut-tart', name: 'Coconut Tart', emoji: '🥥', color: 'white' },
  { id: 'coconut-cheesecake', name: 'Coconut Cheesecake', emoji: '🥥', color: 'white' },
  { id: 'coconut-macaroons', name: 'Coconut Macaroons', emoji: '🥥', color: 'white' },
  { id: 'coconut-bars', name: 'Coconut Bars', emoji: '🥥', color: 'brown' },
  { id: 'coconut-energy-balls', name: 'Coconut Energy Balls', emoji: '🥥', color: 'brown' },
  { id: 'coconut-truffles', name: 'Coconut Truffles', emoji: '🥥', color: 'brown' },
  { id: 'coconut-fudge', name: 'Coconut Fudge', emoji: '🥥', color: 'brown' },
  { id: 'coconut-brittle', name: 'Coconut Brittle', emoji: '🥥', color: 'brown' },
  { id: 'coconut-toffee', name: 'Coconut Toffee', emoji: '🥥', color: 'brown' },
  { id: 'coconut-caramel', name: 'Coconut Caramel', emoji: '🥥', color: 'brown' },
  { id: 'coconut-butterscotch', name: 'Coconut Butterscotch', emoji: '🥥', color: 'brown' },
  { id: 'coconut-praline', name: 'Coconut Praline', emoji: '🥥', color: 'brown' },
  { id: 'coconut-nougat', name: 'Coconut Nougat', emoji: '🥥', color: 'white' },
  { id: 'coconut-marshmallow', name: 'Coconut Marshmallow', emoji: '🥥', color: 'white' },
  { id: 'coconut-divinity', name: 'Coconut Divinity', emoji: '🥥', color: 'white' },
  { id: 'coconut-penuche', name: 'Coconut Penuche', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-nuts', name: 'Coconut Candied Nuts', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-fruit', name: 'Coconut Candied Fruit', emoji: '🥥', color: 'red' },
  { id: 'coconut-candied-peel', name: 'Coconut Candied Peel', emoji: '🥥', color: 'orange' },
  { id: 'coconut-candied-ginger', name: 'Coconut Candied Ginger', emoji: '🥥', color: 'yellow' },
  { id: 'coconut-candied-citrus', name: 'Coconut Candied Citrus', emoji: '🥥', color: 'orange' },
  { id: 'coconut-candied-cherry', name: 'Coconut Candied Cherry', emoji: '🥥', color: 'red' },
  { id: 'coconut-candied-pineapple', name: 'Coconut Candied Pineapple', emoji: '🥥', color: 'yellow' },
  { id: 'coconut-candied-mango', name: 'Coconut Candied Mango', emoji: '🥥', color: 'orange' },
  { id: 'coconut-candied-papaya', name: 'Coconut Candied Papaya', emoji: '🥥', color: 'orange' },
  { id: 'coconut-candied-guava', name: 'Coconut Candied Guava', emoji: '🥥', color: 'pink' },
  { id: 'coconut-candied-banana', name: 'Coconut Candied Banana', emoji: '🥥', color: 'yellow' },
  { id: 'coconut-candied-coconut', name: 'Coconut Candied Coconut', emoji: '🥥', color: 'white' },
  { id: 'coconut-candied-almond', name: 'Coconut Candied Almond', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-pecan', name: 'Coconut Candied Pecan', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-walnut', name: 'Coconut Candied Walnut', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-hazelnut', name: 'Coconut Candied Hazelnut', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-macadamia', name: 'Coconut Candied Macadamia', emoji: '🥥', color: 'white' },
  { id: 'coconut-candied-pistachio', name: 'Coconut Candied Pistachio', emoji: '🥥', color: 'green' },
  { id: 'coconut-candied-cashew', name: 'Coconut Candied Cashew', emoji: '🥥', color: 'white' },
  { id: 'coconut-candied-brazil-nut', name: 'Coconut Candied Brazil Nut', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-pine-nut', name: 'Coconut Candied Pine Nut', emoji: '🥥', color: 'white' },
  { id: 'coconut-candied-chestnut', name: 'Coconut Candied Chestnut', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-acorn', name: 'Coconut Candied Acorn', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-beechnut', name: 'Coconut Candied Beechnut', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-chinquapin', name: 'Coconut Candied Chinquapin', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-ginkgo', name: 'Coconut Candied Ginkgo', emoji: '🥥', color: 'yellow' },
  { id: 'coconut-candied-cedar-nut', name: 'Coconut Candied Cedar Nut', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-cypress-nut', name: 'Coconut Candied Cypress Nut', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-juniper-berry', name: 'Coconut Candied Juniper Berry', emoji: '🥥', color: 'blue' },
  { id: 'coconut-candied-spruce-tip', name: 'Coconut Candied Spruce Tip', emoji: '🥥', color: 'green' },
  { id: 'coconut-candied-fir-tip', name: 'Coconut Candied Fir Tip', emoji: '🥥', color: 'green' },
  { id: 'coconut-candied-pine-tip', name: 'Coconut Candied Pine Tip', emoji: '🥥', color: 'green' },
  { id: 'coconut-candied-hemlock-tip', name: 'Coconut Candied Hemlock Tip', emoji: '🥥', color: 'green' },
  { id: 'coconut-candied-yew-berry', name: 'Coconut Candied Yew Berry', emoji: '🥥', color: 'red' },
  { id: 'coconut-candied-mistletoe-berry', name: 'Coconut Candied Mistletoe Berry', emoji: '🥥', color: 'white' },
  { id: 'coconut-candied-holly-berry', name: 'Coconut Candied Holly Berry', emoji: '🥥', color: 'red' },
  { id: 'coconut-candied-ivy-berry', name: 'Coconut Candied Ivy Berry', emoji: '🥥', color: 'black' },
  { id: 'coconut-candied-nightshade-berry', name: 'Coconut Candied Nightshade Berry', emoji: '🥥', color: 'black' },
  { id: 'coconut-candied-oleander-berry', name: 'Coconut Candied Oleander Berry', emoji: '🥥', color: 'pink' },
  { id: 'coconut-candied-lily-berry', name: 'Coconut Candied Lily Berry', emoji: '🥥', color: 'white' },
  { id: 'coconut-candied-tulip-berry', name: 'Coconut Candied Tulip Berry', emoji: '🥥', color: 'red' },
  { id: 'coconut-candied-daffodil-berry', name: 'Coconut Candied Daffodil Berry', emoji: '🥥', color: 'yellow' },
  { id: 'coconut-candied-hyacinth-berry', name: 'Coconut Candied Hyacinth Berry', emoji: '🥥', color: 'purple' },
  { id: 'coconut-candied-iris-berry', name: 'Coconut Candied Iris Berry', emoji: '🥥', color: 'purple' },
  { id: 'coconut-candied-orchid-berry', name: 'Coconut Candied Orchid Berry', emoji: '🥥', color: 'pink' },
  { id: 'coconut-candied-lotus-berry', name: 'Coconut Candied Lotus Berry', emoji: '🥥', color: 'pink' },
  { id: 'coconut-candied-water-lily-berry', name: 'Coconut Candied Water Lily Berry', emoji: '🥥', color: 'white' },
  { id: 'coconut-candied-lily-of-the-valley', name: 'Coconut Candied Lily of the Valley', emoji: '🥥', color: 'white' },
  { id: 'coconut-candied-snowdrop-berry', name: 'Coconut Candied Snowdrop Berry', emoji: '🥥', color: 'white' },
  { id: 'coconut-candied-crocus-berry', name: 'Coconut Candied Crocus Berry', emoji: '🥥', color: 'purple' },
  { id: 'coconut-candied-glory-of-the-snow', name: 'Coconut Candied Glory of the Snow', emoji: '🥥', color: 'blue' },
  { id: 'coconut-candied-siberian-squill', name: 'Coconut Candied Siberian Squill', emoji: '🥥', color: 'blue' },
  { id: 'coconut-candied-winter-aconite', name: 'Coconut Candied Winter Aconite', emoji: '🥥', color: 'yellow' },
  { id: 'coconut-candied-hellebore', name: 'Coconut Candied Hellebore', emoji: '🥥', color: 'green' },
  { id: 'coconut-candied-christmas-rose', name: 'Coconut Candied Christmas Rose', emoji: '🥥', color: 'white' },
  { id: 'coconut-candied-lenten-rose', name: 'Coconut Candied Lenten Rose', emoji: '🥥', color: 'purple' },
  { id: 'coconut-candied-stinking-hellebore', name: 'Coconut Candied Stinking Hellebore', emoji: '🥥', color: 'green' },
  { id: 'coconut-candied-bear\'s-foot', name: 'Coconut Candied Bear\'s Foot', emoji: '🥥', color: 'yellow' },
  { id: 'coconut-candied-pig\'s-foot', name: 'Coconut Candied Pig\'s Foot', emoji: '🥥', color: 'pink' },
  { id: 'coconut-candied-deer\'s-foot', name: 'Coconut Candied Deer\'s Foot', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-hare\'s-foot', name: 'Coconut Candied Hare\'s Foot', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-rabbit\'s-foot', name: 'Coconut Candied Rabbit\'s Foot', emoji: '🥥', color: 'white' },
  { id: 'coconut-candied-squirrel\'s-foot', name: 'Coconut Candied Squirrel\'s Foot', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-fox\'s-foot', name: 'Coconut Candied Fox\'s Foot', emoji: '🥥', color: 'orange' },
  { id: 'coconut-candied-wolf\'s-foot', name: 'Coconut Candied Wolf\'s Foot', emoji: '🥥', color: 'gray' },
  { id: 'coconut-candied-cat\'s-foot', name: 'Coconut Candied Cat\'s Foot', emoji: '🥥', color: 'pink' },
  { id: 'coconut-candied-dog\'s-foot', name: 'Coconut Candied Dog\'s Foot', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-horse\'s-foot', name: 'Coconut Candied Horse\'s Foot', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-mule\'s-foot', name: 'Coconut Candied Mule\'s Foot', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-donkey\'s-foot', name: 'Coconut Candied Donkey\'s Foot', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-camel\'s-foot', name: 'Coconut Candied Camel\'s Foot', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-elephant\'s-foot', name: 'Coconut Candied Elephant\'s Foot', emoji: '🥥', color: 'gray' },
  { id: 'coconut-candied-giraffe\'s-foot', name: 'Coconut Candied Giraffe\'s Foot', emoji: '🥥', color: 'yellow' },
  { id: 'coconut-candied-zebra\'s-foot', name: 'Coconut Candied Zebra\'s Foot', emoji: '🥥', color: 'black' },
  { id: 'coconut-candied-lion\'s-foot', name: 'Coconut Candied Lion\'s Foot', emoji: '🥥', color: 'yellow' },
  { id: 'coconut-candied-tiger\'s-foot', name: 'Coconut Candied Tiger\'s Foot', emoji: '🥥', color: 'orange' },
  { id: 'coconut-candied-leopard\'s-foot', name: 'Coconut Candied Leopard\'s Foot', emoji: '🥥', color: 'yellow' },
  { id: 'coconut-candied-jaguar\'s-foot', name: 'Coconut Candied Jaguar\'s Foot', emoji: '🥥', color: 'yellow' },
  { id: 'coconut-candied-cheetah\'s-foot', name: 'Coconut Candied Cheetah\'s Foot', emoji: '🥥', color: 'yellow' },
  { id: 'coconut-candied-panther\'s-foot', name: 'Coconut Candied Panther\'s Foot', emoji: '🥥', color: 'black' },
  { id: 'coconut-candied-puma\'s-foot', name: 'Coconut Candied Puma\'s Foot', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-cougar\'s-foot', name: 'Coconut Candied Cougar\'s Foot', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-lynx\'s-foot', name: 'Coconut Candied Lynx\'s Foot', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-bobcat\'s-foot', name: 'Coconut Candied Bobcat\'s Foot', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-ocelot\'s-foot', name: 'Coconut Candied Ocelot\'s Foot', emoji: '🥥', color: 'yellow' },
  { id: 'coconut-candied-margay\'s-foot', name: 'Coconut Candied Margay\'s Foot', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-oncilla\'s-foot', name: 'Coconut Candied Oncilla\'s Foot', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-kodkod\'s-foot', name: 'Coconut Candied Kodkod\'s Foot', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-geoffroy\'s-cat-foot', name: 'Coconut Candied Geoffroy\'s Cat Foot', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-andean-mountain-cat-foot', name: 'Coconut Candied Andean Mountain Cat Foot', emoji: '🥥', color: 'gray' },
  { id: 'coconut-candied-pampas-cat-foot', name: 'Coconut Candied Pampas Cat Foot', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-colocolo-foot', name: 'Coconut Candied Colocolo Foot', emoji: '🥥', color: 'brown' },
  { id: 'coconut-candied-andean-cat-foot', name: 'Coconut Candied Andean Cat Foot', emoji: '🥥', color: 'gray' },
  { id: 'coconut-candied-mountain-cat-foot', name: 'Coconut Candied Mountain Cat Foot', emoji: '🥥', color: 'gray' },
  { id: 'coconut-candied-cat-foot', name: 'Coconut Candied Cat Foot', emoji: '🥥', color: 'pink' },
  { id: 'coconut-candied-dog-foot', name: 'Coconut Candied Dog Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-puppy-foot', name: 'Coconut Candied Puppy Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-kitten-foot', name: 'Coconut Candied Kitten Foot', emoji: '🐾', color: 'pink' },
  { id: 'coconut-candied-bunny-foot', name: 'Coconut Candied Bunny Foot', emoji: '🐾', color: 'white' },
  { id: 'coconut-candied-hamster-foot', name: 'Coconut Candied Hamster Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-gerbil-foot', name: 'Coconut Candied Gerbil Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-mouse-foot', name: 'Coconut Candied Mouse Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-rat-foot', name: 'Coconut Candied Rat Foot', emoji: '🐾', color: 'gray' },
  { id: 'coconut-candied-guinea-pig-foot', name: 'Coconut Candied Guinea Pig Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-chinchilla-foot', name: 'Coconut Candied Chinchilla Foot', emoji: '🐾', color: 'gray' },
  { id: 'coconut-candied-degu-foot', name: 'Coconut Candied Degu Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-mole-foot', name: 'Coconut Candied Mole Foot', emoji: '🐾', color: 'black' },
  { id: 'coconut-candied-shrew-foot', name: 'Coconut Candied Shrew Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-vole-foot', name: 'Coconut Candied Vole Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-lemming-foot', name: 'Coconut Candied Lemming Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-muskrat-foot', name: 'Coconut Candied Muskrat Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-beaver-foot', name: 'Coconut Candied Beaver Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-porcupine-foot', name: 'Coconut Candied Porcupine Foot', emoji: '🐾', color: 'black' },
  { id: 'coconut-candied-hedgehog-foot', name: 'Coconut Candied Hedgehog Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-tenrec-foot', name: 'Coconut Candied Tenrec Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-golden-mole-foot', name: 'Coconut Candied Golden Mole Foot', emoji: '🐾', color: 'gold' },
  { id: 'coconut-candied-marsupial-mole-foot', name: 'Coconut Candied Marsupial Mole Foot', emoji: '🐾', color: 'pink' },
  { id: 'coconut-candied-echidna-foot', name: 'Coconut Candied Echidna Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-platypus-foot', name: 'Coconut Candied Platypus Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-kangaroo-foot', name: 'Coconut Candied Kangaroo Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-wallaby-foot', name: 'Coconut Candied Wallaby Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-quokka-foot', name: 'Coconut Candied Quokka Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-wombat-foot', name: 'Coconut Candied Wombat Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-koala-foot', name: 'Coconut Candied Koala Foot', emoji: '🐾', color: 'gray' },
  { id: 'coconut-candied-tasmanian-devil-foot', name: 'Coconut Candied Tasmanian Devil Foot', emoji: '🐾', color: 'black' },
  { id: 'coconut-candied-numbat-foot', name: 'Coconut Candied Numbat Foot', emoji: '🐾', color: 'orange' },
  { id: 'coconut-candied-bilby-foot', name: 'Coconut Candied Bilby Foot', emoji: '🐾', color: 'gray' },
  { id: 'coconut-candied-bandicoot-foot', name: 'Coconut Candied Bandicoot Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-potoroo-foot', name: 'Coconut Candied Potoroo Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-bettong-foot', name: 'Coconut Candied Bettong Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-quoll-foot', name: 'Coconut Candied Quoll Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-dunnart-foot', name: 'Coconut Candied Dunnart Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-planigale-foot', name: 'Coconut Candied Planigale Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-ningaui-foot', name: 'Coconut Candied Ningaui Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-kultarr-foot', name: 'Coconut Candied Kultarr Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-wood-mouse-foot', name: 'Coconut Candied Wood Mouse Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-harvest-mouse-foot', name: 'Coconut Candied Harvest Mouse Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-deer-mouse-foot', name: 'Coconut Candied Deer Mouse Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-white-footed-mouse-foot', name: 'Coconut Candied White-footed Mouse Foot', emoji: '🐾', color: 'white' },
  { id: 'coconut-candied-cotton-mouse-foot', name: 'Coconut Candied Cotton Mouse Foot', emoji: '🐾', color: 'white' },
  { id: 'coconut-candied-rice-mouse-foot', name: 'Coconut Candied Rice Mouse Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-silky-mouse-foot', name: 'Coconut Candied Silky Mouse Foot', emoji: '🐾', color: 'gray' },
  { id: 'coconut-candied-grasshopper-mouse-foot', name: 'Coconut Candied Grasshopper Mouse Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-banjo-mouse-foot', name: 'Coconut Candied Banjo Mouse Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-spinifex-mouse-foot', name: 'Coconut Candied Spinifex Mouse Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-sand-mouse-foot', name: 'Coconut Candied Sand Mouse Foot', emoji: '🐾', color: 'yellow' },
  { id: 'coconut-candied-pebble-mound-mouse-foot', name: 'Coconut Candied Pebble Mound Mouse Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-golden-mouse-foot', name: 'Coconut Candied Golden Mouse Foot', emoji: '🐾', color: 'gold' },
  { id: 'coconut-candied-pygmy-mouse-foot', name: 'Coconut Candied Pygmy Mouse Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-house-mouse-foot', name: 'Coconut Candied House Mouse Foot', emoji: '🐾', color: 'gray' },
  { id: 'coconut-candied-field-mouse-foot', name: 'Coconut Candied Field Mouse Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-meadow-mouse-foot', name: 'Coconut Candied Meadow Mouse Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-forest-mouse-foot', name: 'Coconut Candied Forest Mouse Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-jumping-mouse-foot', name: 'Coconut Candied Jumping Mouse Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-kangaroo-mouse-foot', name: 'Coconut Candied Kangaroo Mouse Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-hopping-mouse-foot', name: 'Coconut Candied Hopping Mouse Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-pocket-mouse-foot', name: 'Coconut Candied Pocket Mouse Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-pocket-gopher-foot', name: 'Coconut Candied Pocket Gopher Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-pocket-rat-foot', name: 'Coconut Candied Pocket Rat Foot', emoji: '🐾', color: 'brown' },
  { id: 'coconut-candied-kangaroo-rat-foot', name: 'Coconut Candied Kangaroo Rat Foot', emoji: '🐾', color: 'brown' },
];

export const INITIAL_HABITS: Habit[] = [
  { id: 'h1', title: 'Morning Glass of Water & Lemon', emoji: '🍋', completedToday: true, streak: 4 },
  { id: 'h2', title: 'Gua Sha & Skincare Ritual', emoji: '🧖‍♀️', completedToday: true, streak: 7 },
  { id: 'h3', title: 'Pilates or 20-min Hot Girl Walk', emoji: '🎧', completedToday: false, streak: 3 },
  { id: 'h4', title: 'Read 15 pages of inspiring book', emoji: '📖', completedToday: false, streak: 5 },
  { id: 'h5', title: 'Write 3 things I am grateful for', emoji: '✨', completedToday: false, streak: 12 },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 't-1',
    title: 'Morning Matcha Latte & Romanticize Breakfast 🍵✨',
    notes: 'Froth almond milk with vanilla syrup, sprinkle cinnamon, and sit by the sunny window.',
    completed: true,
    completedAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    createdAt: new Date().toISOString(),
    dueDate: new Date().toISOString().split('T')[0],
    dueTime: '09:00',
    priority: 'important',
    energy: 'cozy',
    category: 'daily',
    isPinned: true,
    subtasks: [
      { id: 'st-1', text: 'Whisk ceremonial grade matcha', completed: true },
      { id: 'st-2', text: 'Toast sourdough bread with avocado', completed: true },
      { id: 'st-3', text: 'Light rose candle', completed: true },
    ],
    recurring: 'daily',
    tags: ['morning routine', 'matcha', 'cozy'],
  },
  {
    id: 't-2',
    title: 'Submit Project Presentation Deck 🎀💻',
    notes: 'Double check charts, pastel color schemes, and export PDF deck for the team.',
    completed: false,
    createdAt: new Date().toISOString(),
    dueDate: new Date().toISOString().split('T')[0],
    dueTime: '15:30',
    priority: 'urgent',
    energy: 'boss',
    category: 'career',
    isPinned: true,
    subtasks: [
      { id: 'st-4', text: 'Review slide typography & spacing', completed: true },
      { id: 'st-5', text: 'Write executive summary bullet points', completed: false },
      { id: 'st-6', text: 'Send email to team with link', completed: false },
    ],
    recurring: 'none',
    tags: ['deadline', 'work', 'girlboss'],
  },
  {
    id: 't-3',
    title: 'Evening Self-Care & Korean Face Mask 🧖‍♀️✨',
    notes: 'Hyaluronic acid serum, deep repair hair mask, and lavender pillow mist.',
    completed: false,
    createdAt: new Date().toISOString(),
    dueDate: new Date().toISOString().split('T')[0],
    dueTime: '21:00',
    priority: 'important',
    energy: 'cozy',
    category: 'glam',
    isPinned: false,
    subtasks: [
      { id: 'st-7', text: 'Double cleanse with cleansing balm', completed: false },
      { id: 'st-8', text: 'Put on sheet mask for 20 mins', completed: false },
      { id: 'st-9', text: 'Sip chamomile tea with honey', completed: false },
    ],
    recurring: 'none',
    tags: ['skincare', 'glow-up', 'relax'],
  },
  {
    id: 't-4',
    title: 'Order Fresh Pink Peonies & Strawberries 💐🍓',
    notes: 'Local farmers market or florist shop on 5th avenue.',
    completed: false,
    createdAt: new Date().toISOString(),
    dueDate: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    priority: 'soft',
    energy: 'flow',
    category: 'shopping',
    isPinned: false,
    subtasks: [],
    recurring: 'weekly',
    tags: ['aesthetic', 'home', 'flowers'],
  },
  {
    id: 't-5',
    title: 'Finish 2 chapters of French History & Vocabulary 🇫🇷📚',
    notes: 'Practice Duolingo streak and write down 10 new chic adjectives.',
    completed: false,
    createdAt: new Date().toISOString(),
    dueDate: new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0],
    priority: 'soft',
    energy: 'flow',
    category: 'study',
    isPinned: false,
    subtasks: [
      { id: 'st-10', text: '25 min focus timer', completed: false },
      { id: 'st-11', text: 'Review flashcards on phone', completed: false },
    ],
    recurring: 'none',
    tags: ['languages', 'smart girl', 'paris'],
  },
];
