import { Category, Habit, Task } from '../types/todo';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'all', name: 'All Cute Tasks', emoji: '🎀', color: 'pink' },
  { id: 'daily', name: 'Daily Routine', emoji: '🌸', color: 'rose' },
  { id: 'glam', name: 'Self-Care & Glam', emoji: '💄', color: 'fuchsia' },
  { id: 'study', name: 'Smart Girl Era', emoji: '📚', color: 'purple' },
  { id: 'career', name: 'Girl Boss Moves', emoji: '💼', color: 'emerald' },
  { id: 'shopping', name: 'Pink Wishlist', emoji: '🛍️', color: 'amber' },
  { id: 'travel', name: 'Dream Destinations', emoji: '✈️', color: 'sky' },
];

export const INITIAL_HABITS: Habit[] = [
  { id: 'h1', title: 'Morning Glass of Water & Lemon', emoji: '🍋', completedToday: true, streak: 4 },
  { id: 'h2', title: 'Gua Sha & Skincare Ritual', emoji: '🧖‍♀️', completedToday: true, streak: 7 },
  { id: 'h3', title: 'Pilates or 20-min Hot Girl Walk', emoji: '🎧', completedToday: false, streak: 3 },
  { id: 'h4', title: 'Read 15 pages of inspiring book', emoji: '📖', completedToday: false, streak: 5 },
  { id: 'h5', title: 'Write 3 things I am grateful for', emoji: '✨', completedToday: false, streak: 12 },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 't-1',
    title: 'Morning Matcha Latte & Romanticize Breakfast 🍵✨',
    notes: 'Froth almond milk with vanilla syrup, sprinkle cinnamon, and sit by the sunny window.',
    completed: true,
    completedAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    createdAt: new Date().toISOString(),
    dueDate: new Date().toISOString().split('T')[0],
    dueTime: '09:00',
    priority: 'important',
    energy: 'cozy',
    category: 'daily',
    isPinned: true,
    subtasks: [
      { id: 'st-1', text: 'Whisk ceremonial grade matcha', completed: true },
      { id: 'st-2', text: 'Toast sourdough bread with avocado', completed: true },
      { id: 'st-3', text: 'Light rose candle', completed: true },
    ],
    recurring: 'daily',
    tags: ['morning routine', 'matcha', 'cozy'],
  },
  {
    id: 't-2',
    title: 'Submit Project Presentation Deck 🎀💻',
    notes: 'Double check charts, pastel color schemes, and export PDF deck for the team.',
    completed: false,
    createdAt: new Date().toISOString(),
    dueDate: new Date().toISOString().split('T')[0],
    dueTime: '15:30',
    priority: 'urgent',
    energy: 'boss',
    category: 'career',
    isPinned: true,
    subtasks: [
      { id: 'st-4', text: 'Review slide typography & spacing', completed: true },
      { id: 'st-5', text: 'Write executive summary bullet points', completed: false },
      { id: 'st-6', text: 'Send email to team with link', completed: false },
    ],
    recurring: 'none',
    tags: ['deadline', 'work', 'girlboss'],
  },
  {
    id: 't-3',
    title: 'Evening Self-Care & Korean Face Mask 🧖‍♀️✨',
    notes: 'Hyaluronic acid serum, deep repair hair mask, and lavender pillow mist.',
    completed: false,
    createdAt: new Date().toISOString(),
    dueDate: new Date().toISOString().split('T')[0],
    dueTime: '21:00',
    priority: 'important',
    energy: 'cozy',
    category: 'glam',
    isPinned: false,
    subtasks: [
      { id: 'st-7', text: 'Double cleanse with cleansing balm', completed: false },
      { id: 'st-8', text: 'Put on sheet mask for 20 mins', completed: false },
      { id: 'st-9', text: 'Sip chamomile tea with honey', completed: false },
    ],
    recurring: 'none',
    tags: ['skincare', 'glow-up', 'relax'],
  },
  {
    id: 't-4',
    title: 'Order Fresh Pink Peonies & Strawberries 💐🍓',
    notes: 'Local farmers market or florist shop on 5th avenue.',
    completed: false,
    createdAt: new Date().toISOString(),
    dueDate: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    priority: 'soft',
    energy: 'flow',
    category: 'shopping',
    isPinned: false,
    subtasks: [],
    recurring: 'weekly',
    tags: ['aesthetic', 'home', 'flowers'],
  },
  {
    id: 't-5',
    title: 'Finish 2 chapters of French History & Vocabulary 🇫🇷📚',
    notes: 'Practice Duolingo streak and write down 10 new chic adjectives.',
    completed: false,
    createdAt: new Date().toISOString(),
    dueDate: new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0],
    priority: 'soft',
    energy: 'flow',
    category: 'study',
    isPinned: false,
    subtasks: [
      { id: 'st-10', text: '25 min focus timer', completed: false },
      { id: 'st-11', text: 'Review flashcards on phone', completed: false },
    ],
    recurring: 'none',
    tags: ['languages', 'smart girl', 'paris'],
  },
];
