import { Sticker } from '../types/todo';

export const ALL_STICKERS: Sticker[] = [
  {
    id: 'satin_bow',
    name: 'Satin Silk Bow',
    emoji: '🎀',
    description: 'Awarded for starting your journey in style.',
    requiredPetals: 0,
    unlocked: true,
  },
  {
    id: 'ballet_slippers',
    name: 'Ballet Slippers',
    emoji: '🩰',
    description: 'Graceful progress! Unlocked at 30 petals.',
    requiredPetals: 30,
    unlocked: false,
  },
  {
    id: 'strawberry_cake',
    name: 'Strawberry Shortcake',
    emoji: '🍰',
    description: 'Sweet productivity! Unlocked at 60 petals.',
    requiredPetals: 60,
    unlocked: false,
  },
  {
    id: 'pearl_necklace',
    name: 'Pearl Necklace',
    emoji: '📿',
    description: 'Classic elegance. Unlocked at 100 petals.',
    requiredPetals: 100,
    unlocked: false,
  },
  {
    id: 'sparkle_stars',
    name: 'Celestial Sparkle',
    emoji: '✨',
    description: 'Shining bright! Unlocked at 150 petals.',
    requiredPetals: 150,
    unlocked: false,
  },
  {
    id: 'cherry_blossom',
    name: 'Cherry Blossom',
    emoji: '🌸',
    description: 'Blooming into your best self. Unlocked at 200 petals.',
    requiredPetals: 200,
    unlocked: false,
  },
  {
    id: 'chanel_lipstick',
    name: 'Rosewater Gloss',
    emoji: '💄',
    description: 'Glow up in progress. Unlocked at 250 petals.',
    requiredPetals: 250,
    unlocked: false,
  },
  {
    id: 'matcha_latte',
    name: 'Iced Matcha Oat',
    emoji: '🍵',
    description: 'Calm, focused, and nourished. Unlocked at 300 petals.',
    requiredPetals: 300,
    unlocked: false,
  },
  {
    id: 'princess_crown',
    name: 'Princess Tiara',
    emoji: '👑',
    description: 'Conquered your to-do kingdom! Unlocked at 400 petals.',
    requiredPetals: 400,
    unlocked: false,
  },
  {
    id: 'golden_heart',
    name: 'Golden Heart',
    emoji: '💖',
    description: 'Ultimate master of self-love and productivity! Unlocked at 500 petals.',
    requiredPetals: 500,
    unlocked: false,
  },
];
